version: "2"

run:
  timeout: 5m

linters:
  default: standard
  enable:
    - govet
    - staticcheck
    - unused
    - errcheck
    - ineffassign
    - unconvert
    - misspell

formatters:
  enable:
    - gofmt
    - goimports
