// Code generated by sqlc-model. DO NOT EDIT.
package content

// UserField identifies one field of User, in declared field order.
type UserField uint8

const (
	UserFieldID UserField = iota
	UserFieldEmail
	UserFieldCount
)
