// Code generated by sqlc-gen-richmodel. DO NOT EDIT.
package content

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

// UserCollection constructs and finds User instances, attached to
// the session that produced it.
type UserCollection struct {
	session *Session
	store   *userStore
}

func newUserCollection(sess *Session) *UserCollection {
	return &UserCollection{session: sess, store: newUserStore(sess.executor)}
}

// New constructs a new, unpersisted User attached to this collection.
func (c *UserCollection) New() *User {
	return &User{coll: c, state: modelStateNew}
}

// Find looks up a persisted User by its configured find operation.
func (c *UserCollection) Find(ctx context.Context, id pgtype.UUID) (*User, error) {
	rec, err := c.store.find(ctx, userRecord{
		ID: id,
	})
	if err != nil {
		return nil, err
	}
	u := &User{coll: c, state: modelStatePersisted}
	u.current, u.original = rec, rec
	return u, nil
}
