// Code generated by sqlc-gen-richmodel. DO NOT EDIT.
package content

import (
	"context"
	"fmt"
)

// userStore executes User's configured sqlc queries directly via
// pgx, using each query's already-validated, already-parameterized SQL text
// exactly as sqlc's own generated code would (sqlc-gen-go embeds this same
// query.Text verbatim as its query constant) — the query itself remains
// sqlc's statically-verified output; this adapter only executes it.
type userStore struct {
	executor richmodelExecutor
}

func newUserStore(executor richmodelExecutor) *userStore {
	return &userStore{executor: executor}
}

func (s *userStore) find(ctx context.Context, rec userRecord) (userRecord, error) {
	var out userRecord
	var scanEmail string
	row := s.executor.QueryRow(ctx, "SELECT id, email FROM users WHERE id = $1;", rec.ID)
	if err := row.Scan(&out.ID, &scanEmail); err != nil {
		return userRecord{}, err
	}
	email, err := NewEmail(scanEmail)
	if err != nil {
		return userRecord{}, fmt.Errorf("User.Email: %w", err)
	}
	out.Email = email
	return out, nil
}

func (s *userStore) insert(ctx context.Context, rec userRecord) (userRecord, error) {
	var out userRecord
	var scanEmail string
	row := s.executor.QueryRow(ctx, "INSERT INTO users (email) VALUES ($1) RETURNING id, email;", rec.Email.String())
	if err := row.Scan(&out.ID, &scanEmail); err != nil {
		return userRecord{}, err
	}
	email, err := NewEmail(scanEmail)
	if err != nil {
		return userRecord{}, fmt.Errorf("User.Email: %w", err)
	}
	out.Email = email
	return out, nil
}

func (s *userStore) update(ctx context.Context, rec userRecord) (userRecord, error) {
	var out userRecord
	var scanEmail string
	row := s.executor.QueryRow(ctx, "UPDATE users SET email = $1 WHERE id = $2 RETURNING id, email;", rec.Email.String(), rec.ID)
	if err := row.Scan(&out.ID, &scanEmail); err != nil {
		return userRecord{}, err
	}
	email, err := NewEmail(scanEmail)
	if err != nil {
		return userRecord{}, fmt.Errorf("User.Email: %w", err)
	}
	out.Email = email
	return out, nil
}

func (s *userStore) refresh(ctx context.Context, rec userRecord) (userRecord, error) {
	var out userRecord
	var scanEmail string
	row := s.executor.QueryRow(ctx, "SELECT id, email FROM users WHERE id = $1;", rec.ID)
	if err := row.Scan(&out.ID, &scanEmail); err != nil {
		return userRecord{}, err
	}
	email, err := NewEmail(scanEmail)
	if err != nil {
		return userRecord{}, fmt.Errorf("User.Email: %w", err)
	}
	out.Email = email
	return out, nil
}
