package codegen

import (
	"fmt"
	"strings"
	"unicode"

	"github.com/macoaure/sqlc-gen-richmodel/internal/diagnostics"
	"github.com/macoaure/sqlc-gen-richmodel/internal/plan"
)

const collectionTemplate = `// Code generated by sqlc-gen-richmodel. DO NOT EDIT.
package {{.Package}}

import (
	"context"

	"github.com/jackc/pgx/v5/pgxpool"
{{- range .Imports}}
	"{{.}}"
{{- end}}
)

// {{.Row}}Collection constructs and finds {{.Row}} instances, attached to
// the session that produced it.
type {{.Row}}Collection struct {
	session *Session
	store   *{{.StoreType}}
}

func new{{.Row}}Collection(sess *Session, pool *pgxpool.Pool) *{{.Row}}Collection {
	return &{{.Row}}Collection{session: sess, store: new{{.Row}}Store(pool)}
}

// New constructs a new, unpersisted {{.Row}} attached to this collection.
func (c *{{.Row}}Collection) New() *{{.Row}} {
	return &{{.Row}}{coll: c, state: modelStateNew}
}
{{if .HasFind}}
// Find looks up a persisted {{.Row}} by its configured find operation.
func (c *{{.Row}}Collection) Find(ctx context.Context{{range .FindParams}}, {{.ParamName}} {{.GoType}}{{end}}) (*{{.Row}}, error) {
	rec, err := c.store.find(ctx, {{.RecordType}}{
{{- range .FindParams}}
		{{.GoField}}: {{.ParamName}},
{{- end}}
	})
	if err != nil {
		return nil, err
	}
	u := &{{.Row}}{coll: c, state: modelStatePersisted}
	u.current, u.original = rec, rec
	return u, nil
}
{{end}}
`

type collectionParamData struct {
	ParamName string
	GoField   string
	GoType    string
}

type collectionTemplateData struct {
	Package    string
	Row        string
	StoreType  string
	RecordType string
	HasFind    bool
	FindParams []collectionParamData
	Imports    []string
}

// lowerFirst produces an idiomatic unexported parameter name from an
// exported Go field name, e.g. "Name" -> "name". A field name that's
// entirely initialism-upper-case (e.g. "ID") lowercases in full ("id")
// rather than producing an awkward "iD".
func lowerFirst(s string) string {
	if s == "" {
		return s
	}
	if s == strings.ToUpper(s) {
		return strings.ToLower(s)
	}
	r := []rune(s)
	r[0] = unicode.ToLower(r[0])
	return string(r)
}

// RenderCollection renders <model>_collection_gen.go: the New/Find
// entrypoints, per quickstart.md's `sess.Users.New()`/`sess.Users.Find(...)`.
func RenderCollection(ctx plan.ResolvedContext, m plan.ResolvedModel) ([]byte, []diagnostics.Diagnostic) {
	data := collectionTemplateData{
		Package:    ctx.Package,
		Row:        m.Row,
		StoreType:  StoreTypeName(m.Row),
		RecordType: RecordTypeName(m.Row),
		HasFind:    m.Operations.Find != nil,
	}

	var imports []string
	if data.HasFind {
		usedNames := make(map[string]int)
		for _, pb := range sortedParams(m.Operations.Find.Params) {
			name := lowerFirst(pb.Field.GoField)
			usedNames[name]++
			if n := usedNames[name]; n > 1 {
				name = fmt.Sprintf("%s%d", name, n)
			}
			data.FindParams = append(data.FindParams, collectionParamData{
				ParamName: name,
				GoField:   pb.Field.GoField,
				GoType:    pb.Field.GoType.Expr,
			})
			imports = append(imports, pb.Field.GoType.Import)
		}
	}
	data.Imports = uniqueSortedImports(imports...)

	filePath := fmt.Sprintf("%s/%s_collection_gen.go", ctx.Directory, fileStem(m.Row))
	return render(filePath, "collection_gen.go", collectionTemplate, data, ctx.Name, m.Name)
}
