package codegen

import (
	"fmt"
	"strconv"

	"github.com/macoaure/sqlc-model/internal/config"
	"github.com/macoaure/sqlc-model/internal/diagnostics"
	"github.com/macoaure/sqlc-model/internal/plan"
)

const eagerTemplate = `// Code generated by sqlc-model. DO NOT EDIT.
package {{.Package}}

import (
	"context"
{{- range .Imports}}
	"{{.}}"
{{- end}}
)

// {{.PlanType}} accumulates which of {{.Row}}'s eager-loadable relations a
// caller has requested via With<Relation> option constructors.
type {{.PlanType}} struct {
{{- range .Relations}}
	load{{.Name}}   bool
	nested{{.Name}} []func({{.OptionType}}) {{.OptionType}}
{{- end}}
}

// {{.OptionTypeName}} configures one relation to eager-load for a batch of
// {{.Row}} instances (contracts/relation-api.md).
type {{.OptionTypeName}} func(*{{.PlanType}})
{{range .Relations}}{{$rel := .}}
// {{.OptionType}} composes nested eager loads for {{$.Row}}.{{.Name}}'s own
// eager-loadable relations (FR-014) — With<Relation> methods exist only for
// relations on {{.TargetRow}} that themselves have an eager_query configured.
type {{.OptionType}} struct {
{{- range .Nested}}
	load{{.Name}}   bool
	nested{{.Name}} []func({{.OptionType}}) {{.OptionType}}
{{- end}}
}
{{range .Nested}}
// With{{.Name}} requests {{$rel.TargetRow}}.{{.Name}} be eager-loaded as
// part of the same batch request.
func (e {{$rel.OptionType}}) With{{.Name}}(nested ...func({{.OptionType}}) {{.OptionType}}) {{$rel.OptionType}} {
	e.load{{.Name}} = true
	e.nested{{.Name}} = append(append([]func({{.OptionType}}) {{.OptionType}}{}, e.nested{{.Name}}...), nested...)
	return e
}
{{end}}
// With{{.Name}} is a {{$.OptionTypeName}} constructor requesting
// {{$.Row}}.{{.Name}} be eager-loaded (FR-013). Generated only because
// {{.Name}} has an eager_query configured.
func With{{.Name}}(nested ...func({{.OptionType}}) {{.OptionType}}) {{$.OptionTypeName}} {
	return func(p *{{$.PlanType}}) {
		p.load{{.Name}} = true
		p.nested{{.Name}} = append(append([]func({{.OptionType}}) {{.OptionType}}{}, p.nested{{.Name}}...), nested...)
	}
}
{{end}}
// EagerLoad populates the requested relations' canonical caches for every
// element of parents in one batch data-access operation per relation level
// (FR-013, SC-002), including nested relations requested via
// With<Relation>(func(o) { return o.With<Nested>() }) (FR-014), and
// populates each related record's configured inverse cache with the
// already-known parent instance (FR-015).
func (c *{{.CollectionType}}) EagerLoad(ctx context.Context, parents []*{{.Row}}, opts ...{{.OptionTypeName}}) error {
	if len(parents) == 0 {
		return nil
	}
	var p {{.PlanType}}
	for _, opt := range opts {
		opt(&p)
	}
{{range .Relations}}
	if p.load{{.Name}} {
		if err := c.eagerLoad{{.Name}}(ctx, parents, p.nested{{.Name}}); err != nil {
			return err
		}
	}
{{end}}
	return nil
}
{{range .Relations}}{{$rel := .}}
func (c *{{$.CollectionType}}) eagerLoad{{.Name}}(ctx context.Context, parents []*{{$.Row}}, nested []func({{.OptionType}}) {{.OptionType}}) error {
	keys := make([]{{.LocalKeyGoType}}, 0, len(parents))
	byKey := make(map[{{.LocalKeyGoType}}][]*{{$.Row}}, len(parents))
	for _, parent := range parents {
		key := parent.current.{{.LocalKeyGoField}}
		keys = append(keys, key)
		byKey[key] = append(byKey[key], parent)
	}

	rows, err := c.session.executor.Query(ctx, {{.EagerSQL}}, keys)
	if err != nil {
		return err
	}
	defer rows.Close()

	grouped := make(map[{{.LocalKeyGoType}}][]*{{.TargetRow}})
	var allTargets []*{{.TargetRow}}
	for rows.Next() {
		var rec {{.TargetRecordType}}
		if err := rows.Scan({{range $i, $f := .EagerScan}}{{if $i}}, {{end}}&rec.{{$f}}{{end}}); err != nil {
			return err
		}
		t := &{{.TargetRow}}{coll: c.session.{{.TargetCollectionField}}, state: modelStatePersisted}
		t.current, t.original = rec, rec
		fk := rec.{{.ForeignKeyGoField}}
		grouped[fk] = append(grouped[fk], t)
		allTargets = append(allTargets, t)
	}
	if err := rows.Err(); err != nil {
		return err
	}

	for key, ps := range byKey {
		related := grouped[key]
		for _, parent := range ps {
{{- if .ToMany}}
			parent.{{.CacheField}} = related
{{- else}}
			if len(related) > 0 {
				parent.{{.CacheField}} = related[0]
			} else {
				parent.{{.CacheField}} = nil
			}
{{- end}}
			parent.{{.LoadedField}} = true
{{- if .HasInverse}}
			for _, t := range related {
{{- if .InverseToMany}}
				t.{{.InverseCacheField}} = append(t.{{.InverseCacheField}}, parent)
{{- else}}
				t.{{.InverseCacheField}} = parent
{{- end}}
				t.{{.InverseLoadedField}} = true
			}
{{- end}}
		}
	}
{{if .Nested}}
	if len(allTargets) > 0 {
		var opt {{.OptionType}}
		for _, fn := range nested {
			opt = fn(opt)
		}
{{range .Nested}}
		if opt.load{{.Name}} {
			if err := c.session.{{$rel.TargetCollectionField}}.eagerLoad{{.Name}}(ctx, allTargets, opt.nested{{.Name}}); err != nil {
				return err
			}
		}
{{end}}
	}
{{end}}
	return nil
}
{{end}}
`

type eagerNestedData struct {
	Name       string
	OptionType string
}

type eagerRelationData struct {
	Name                  string
	OptionType            string
	TargetRow             string
	TargetRecordType      string
	TargetCollectionField string
	ToMany                bool
	CacheField            string
	LoadedField           string
	LocalKeyGoField       string
	LocalKeyGoType        string
	ForeignKeyGoField     string
	EagerSQL              string
	EagerScan             []string
	HasInverse            bool
	InverseToMany         bool
	InverseCacheField     string
	InverseLoadedField    string
	Nested                []eagerNestedData
}

type eagerTemplateData struct {
	Package        string
	Row            string
	CollectionType string
	PlanType       string
	OptionTypeName string
	Relations      []eagerRelationData
	Imports        []string
}

// hasEagerRelation reports whether m has any relation with an eager_query
// configured — the sole gate for whether m gets an eager_gen.go file at
// all (research.md — eager-load capability is signaled purely by
// eager_query presence).
func hasEagerRelation(m plan.ResolvedModel) bool {
	for _, rel := range m.Relations {
		if rel.EagerQuery != nil {
			return true
		}
	}
	return false
}

// RenderEager renders <model>_eager_gen.go: the eager-load option types and
// batch-loading entry point for every one of m's eager-loadable relations,
// per contracts/relation-api.md. Aggregated per model (not per relation)
// because the plan/option types are shared across all of a model's
// eager-loadable relations.
func RenderEager(ctx plan.ResolvedContext, m plan.ResolvedModel) ([]byte, []diagnostics.Diagnostic) {
	data := eagerTemplateData{
		Package:        ctx.Package,
		Row:            m.Row,
		CollectionType: m.Row + "Collection",
		PlanType:       fileStem(m.Row) + "EagerLoadPlan",
		OptionTypeName: m.Row + "EagerLoadOption",
	}

	var extraImports []string
	for _, rel := range m.Relations {
		if rel.EagerQuery == nil {
			continue
		}
		toMany := rel.Kind == config.HasMany || rel.Kind == config.ManyToMany
		cacheField, loadedField := relationCacheField(rel.Name)

		rd := eagerRelationData{
			Name:                  rel.Name,
			OptionType:            fmt.Sprintf("%s%sEagerLoad", m.Row, rel.Name),
			TargetRow:             rel.Target.Row,
			TargetRecordType:      RecordTypeName(rel.Target.Row),
			TargetCollectionField: CollectionFieldName(rel.Target.Row),
			ToMany:                toMany,
			CacheField:            cacheField,
			LoadedField:           loadedField,
			EagerSQL:              strconv.Quote(rel.EagerQuery.GetText()),
		}
		if rel.LocalKey != nil {
			rd.LocalKeyGoField = rel.LocalKey.GoField
			rd.LocalKeyGoType = rel.LocalKey.GoType.Expr
			extraImports = append(extraImports, rel.LocalKey.GoType.Import)
		}
		if rel.ForeignKeyField != nil {
			rd.ForeignKeyGoField = rel.ForeignKeyField.GoField
		}
		for _, f := range rel.EagerScan {
			rd.EagerScan = append(rd.EagerScan, f.GoField)
		}
		if rel.Inverse != nil {
			rd.HasInverse = true
			rd.InverseToMany = rel.Inverse.Kind == config.HasMany || rel.Inverse.Kind == config.ManyToMany
			invCache, invLoaded := relationCacheField(rel.Inverse.Name)
			rd.InverseCacheField = invCache
			rd.InverseLoadedField = invLoaded
		}
		for _, nrel := range rel.Target.Relations {
			if nrel.EagerQuery == nil {
				continue
			}
			rd.Nested = append(rd.Nested, eagerNestedData{
				Name:       nrel.Name,
				OptionType: fmt.Sprintf("%s%sEagerLoad", rel.Target.Row, nrel.Name),
			})
		}
		data.Relations = append(data.Relations, rd)
	}
	data.Imports = uniqueSortedImports(extraImports...)

	filePath := fmt.Sprintf("%s/%s_eager_gen.go", ctx.Directory, fileStem(m.Row))
	return render(filePath, "eager_gen.go", eagerTemplate, data, ctx.Name, m.Name)
}
