package codegen

import (
	"fmt"

	"github.com/macoaure/sqlc-gen-richmodel/internal/diagnostics"
	"github.com/macoaure/sqlc-gen-richmodel/internal/plan"
)

const fieldsTemplate = `// Code generated by sqlc-gen-richmodel. DO NOT EDIT.
package {{.Package}}

{{range .Models}}{{$model := .}}
// {{$model.Row}}Field identifies one field of {{$model.Row}}, in declared field order.
type {{$model.Row}}Field uint8

const (
{{- range $i, $f := $model.Fields}}
	{{$model.Row}}Field{{$f.GoField}} {{if eq $i 0}}{{$model.Row}}Field = iota{{end}}
{{- end}}
	{{$model.Row}}FieldCount
)
{{end}}
`

type fieldsTemplateData struct {
	Package string
	Models  []*plan.ResolvedModel
}

// RenderFields renders fields_gen.go for one context: one <Model>Field enum
// per model, one constant per field in declared order, regardless of each
// field's policy (contracts/generated-model-api.md "Field identifiers").
func RenderFields(ctx plan.ResolvedContext) ([]byte, []diagnostics.Diagnostic) {
	data := fieldsTemplateData{Package: ctx.Package}
	for i := range ctx.Models {
		data.Models = append(data.Models, &ctx.Models[i])
	}
	filePath := fmt.Sprintf("%s/fields_gen.go", ctx.Directory)
	return render(filePath, "fields_gen.go", fieldsTemplate, data, ctx.Name, "")
}
