package codegen

import (
	"fmt"
	"strings"

	"github.com/macoaure/sqlc-gen-richmodel/internal/config"
	"github.com/macoaure/sqlc-gen-richmodel/internal/diagnostics"
	"github.com/macoaure/sqlc-gen-richmodel/internal/plan"
)

const modelTemplate = `// Code generated by sqlc-gen-richmodel. DO NOT EDIT.
package {{.Package}}

import (
	"context"
	"errors"
	"fmt"
	"strings"
{{- if .NeedsSlices}}
	"slices"
{{- end}}
{{- range .Imports}}
	"{{.}}"
{{- end}}
)

// {{.Row}} is a generated Active-Record-style model. See
// contracts/generated-model-api.md for the full contract every generated
// model satisfies.
type {{.Row}} struct {
	current {{.RecordType}}
	original {{.RecordType}}
	errs map[{{.Row}}Field]error
	state modelState
	coll *{{.Row}}Collection
{{- range .RelationCaches}}
	{{.CacheField}} {{.CacheType}}
	{{.LoadedField}} bool
{{- end}}
}
{{$row := .Row}}
{{range .Fields}}{{if .Readable}}
// {{.GoField}} returns {{$row}}'s current {{.GoField}} value.
func (u *{{$row}}) {{.GoField}}() {{.GoType}} { return u.current.{{.GoField}} }
{{end}}{{end}}
{{range .Fields}}{{if .Settable}}
// Set{{.GoField}} sets {{$row}}'s {{.GoField}} and updates its dirty state.
func (u *{{$row}}) Set{{.GoField}}(value {{.GoType}}) *{{$row}} {
{{- if .Immutable}}
	if !u.IsNew() {
		u.setFieldError({{$row}}Field{{.GoField}}, ErrImmutableField)
		return u
	}
{{- end}}
	u.current.{{.GoField}} = value
	u.clearFieldError({{$row}}Field{{.GoField}})
	return u
}
{{end}}{{end}}
{{range .Fields}}{{if .HasOriginal}}
// Original{{.GoField}} returns {{$row}}'s last-persisted {{.GoField}} value.
func (u *{{$row}}) Original{{.GoField}}() {{.GoType}} { return u.original.{{.GoField}} }
{{end}}{{end}}

func (u *{{.Row}}) fieldEqual(f {{.Row}}Field) bool {
	switch f {
{{- range .Fields}}
	case {{$row}}Field{{.GoField}}:
{{- if .IsSlice}}
		return slices.Equal(u.current.{{.GoField}}, u.original.{{.GoField}})
{{- else}}
		return u.current.{{.GoField}} == u.original.{{.GoField}}
{{- end}}
{{- end}}
	}
	return true
}

// IsDirty reports whether any of fields differ from their original,
// last-persisted values; with no arguments, the whole model is considered.
func (u *{{.Row}}) IsDirty(fields ...{{.Row}}Field) bool {
	if len(fields) == 0 {
		for f := {{.Row}}Field(0); f < {{.Row}}FieldCount; f++ {
			if !u.fieldEqual(f) {
				return true
			}
		}
		return false
	}
	for _, f := range fields {
		if !u.fieldEqual(f) {
			return true
		}
	}
	return false
}

// IsClean is the inverse of IsDirty.
func (u *{{.Row}}) IsClean(fields ...{{.Row}}Field) bool { return !u.IsDirty(fields...) }

// HasChanges reports whether any current field differs from its baseline.
func (u *{{.Row}}) HasChanges() bool {
	if u.state == modelStateDeleted {
		return false
	}
	return u.IsDirty()
}

// DirtyFields returns every dirty field, in declared field order.
func (u *{{.Row}}) DirtyFields() []{{.Row}}Field {
	var out []{{.Row}}Field
	for f := {{.Row}}Field(0); f < {{.Row}}FieldCount; f++ {
		if !u.fieldEqual(f) {
			out = append(out, f)
		}
	}
	return out
}

func (u *{{.Row}}) fieldErr() error {
	if len(u.errs) == 0 {
		return nil
	}
	var errs []error
	for f := {{.Row}}Field(0); f < {{.Row}}FieldCount; f++ {
		if err, ok := u.errs[f]; ok {
			errs = append(errs, err)
		}
	}
	return errors.Join(errs...)
}

// Err aggregates every current validation error; nil if there are none.
func (u *{{.Row}}) Err() error { return u.Validate() }

// Validate combines current field errors with any handwritten cross-field
// validation hook declared in {{.Row}}'s extension file.
func (u *{{.Row}}) Validate() error {
	var custom error
	if v, ok := any(u).(interface{ validate{{.Row}}() error }); ok {
		custom = v.validate{{.Row}}()
	}
	return errors.Join(u.fieldErr(), custom)
}

// HasErrors reports whether {{.Row}} has any current validation error.
func (u *{{.Row}}) HasErrors() bool { return u.Validate() != nil }

// FieldError returns f's current error, or nil.
func (u *{{.Row}}) FieldError(f {{.Row}}Field) error { return u.errs[f] }

// ClearErrors discards every current field error.
func (u *{{.Row}}) ClearErrors() *{{.Row}} {
	u.errs = nil
	return u
}

// setFieldError is the sanctioned way handwritten extension code sets a
// field error without bypassing public setter behavior (FR-019). Setting a
// new error for a field replaces any previous error for that field.
func (u *{{.Row}}) setFieldError(f {{.Row}}Field, err error) *{{.Row}} {
	if u.errs == nil {
		u.errs = make(map[{{.Row}}Field]error)
	}
	u.errs[f] = err
	return u
}

// clearFieldError is the sanctioned way handwritten extension code clears a
// field error without bypassing public setter behavior (FR-019).
func (u *{{.Row}}) clearFieldError(f {{.Row}}Field) *{{.Row}} {
	delete(u.errs, f)
	return u
}

// Exists reports whether {{.Row}} has ever been persisted.
func (u *{{.Row}}) Exists() bool { return u.state != modelStateNew }

// IsPersisted reports whether {{.Row}} currently has a persisted backing row.
func (u *{{.Row}}) IsPersisted() bool { return u.state == modelStatePersisted }

// IsNew reports whether {{.Row}} has never been persisted.
func (u *{{.Row}}) IsNew() bool { return u.state == modelStateNew }

// IsDeleted reports whether {{.Row}} has been deleted.
func (u *{{.Row}}) IsDeleted() bool { return u.state == modelStateDeleted }

// IsAttached reports whether {{.Row}} is attached to an owning session.
func (u *{{.Row}}) IsAttached() bool { return u.coll != nil }

// IsDetached reports whether {{.Row}} has no owning session.
func (u *{{.Row}}) IsDetached() bool { return !u.IsAttached() }

// Detach returns a copy of {{.Row}} without an owning session.
func (u *{{.Row}}) Detach() *{{.Row}} {
	v := *u
	v.coll = nil
	return &v
}

// Save validates first; inserts if new, does nothing if persisted and
// clean, updates if persisted and dirty. Returns ErrModelDeleted or
// ErrModelDetached if {{.Row}} is deleted or not attached.
func (u *{{.Row}}) Save(ctx context.Context) error {
	if u.state == modelStateDeleted {
		return ErrModelDeleted
	}
	if !u.IsAttached() {
		return ErrModelDetached
	}
	if err := u.Validate(); err != nil {
		return err
	}
	switch {
	case u.state == modelStateNew:
		out, err := u.coll.store.insert(ctx, u.current)
		if err != nil {
			return err
		}
		u.current, u.original = out, out
		u.state = modelStatePersisted
		return nil
	case u.IsClean():
		return nil
	default:
{{- if .HasUpdate}}
		out, err := u.coll.store.update(ctx, u.current)
		if err != nil {
			return err
		}
		u.current, u.original = out, out
		return nil
{{- else}}
		return ErrOperationNotConfigured
{{- end}}
	}
}

// Delete deletes {{.Row}}; idempotent if already deleted. Returns
// ErrModelDetached if {{.Row}} is not attached.
func (u *{{.Row}}) Delete(ctx context.Context) error {
	if u.state == modelStateDeleted {
		return nil
	}
	if !u.IsAttached() {
		return ErrModelDetached
	}
	if u.state == modelStateNew {
		return ErrModelNotPersisted
	}
{{- if .HasDelete}}
	if _, err := u.coll.store.delete(ctx, u.current); err != nil {
		return err
	}
	u.original = u.current
	u.state = modelStateDeleted
	return nil
{{- else}}
	return ErrOperationNotConfigured
{{- end}}
}

// Refresh re-hydrates {{.Row}} from the database and re-synchronizes its
// original snapshot. Returns ErrModelDeleted or ErrModelDetached if
// {{.Row}} is deleted or not attached.
func (u *{{.Row}}) Refresh(ctx context.Context) error {
	if u.state == modelStateDeleted {
		return ErrModelDeleted
	}
	if !u.IsAttached() {
		return ErrModelDetached
	}
	if u.state == modelStateNew {
		return ErrModelNotPersisted
	}
{{- if .HasRefresh}}
	out, err := u.coll.store.refresh(ctx, u.current)
	if err != nil {
		return err
	}
	u.current, u.original = out, out
	return nil
{{- else}}
	return ErrOperationNotConfigured
{{- end}}
}

// String renders {{.Row}} for diagnostics, omitting the value of every
// field marked sensitive (FR-014).
func (u *{{.Row}}) String() string {
	fields := []string{
{{- range .Fields}}
{{- if .Sensitive}}
		"{{.GoField}}=<redacted>",
{{- else}}
		fmt.Sprintf("{{.GoField}}=%v", u.current.{{.GoField}}),
{{- end}}
{{- end}}
	}
	return fmt.Sprintf("{{.Row}}{%s}", strings.Join(fields, ", "))
}
`

type modelFieldData struct {
	GoField     string
	GoType      string
	Readable    bool
	Settable    bool
	HasOriginal bool
	Immutable   bool
	Sensitive   bool
	IsSlice     bool
}

type relationCacheFieldData struct {
	CacheField  string
	CacheType   string
	LoadedField string
}

type modelTemplateData struct {
	Package        string
	Row            string
	RecordType     string
	Fields         []modelFieldData
	HasUpdate      bool
	HasDelete      bool
	HasRefresh     bool
	NeedsSlices    bool
	Imports        []string
	RelationCaches []relationCacheFieldData
}

// relationCacheField derives a relation's cache/loaded field name pair, e.g.
// "postsCache"/"postsLoaded" for a relation named "Posts" (data-model.md
// "Relation cache fields on the Generated Model").
func relationCacheField(relationName string) (cacheField, loadedField string) {
	base := lowerFirst(relationName)
	return base + "Cache", base + "Loaded"
}

// RenderModel renders <model>_gen.go: the full generated model API per
// contracts/generated-model-api.md.
func RenderModel(ctx plan.ResolvedContext, m plan.ResolvedModel) ([]byte, []diagnostics.Diagnostic) {
	data := modelTemplateData{
		Package:    ctx.Package,
		Row:        m.Row,
		RecordType: RecordTypeName(m.Row),
		HasUpdate:  m.Operations.Update != nil,
		HasDelete:  m.Operations.Delete != nil,
		HasRefresh: m.Operations.Refresh != nil,
	}

	var imports []string
	for _, f := range m.Fields {
		settable := f.Policy.Fillable || f.Policy.Mutable
		isSlice := strings.HasPrefix(f.GoType.Expr, "[]")
		if isSlice {
			data.NeedsSlices = true
		}
		data.Fields = append(data.Fields, modelFieldData{
			GoField:     f.GoField,
			GoType:      f.GoType.Expr,
			Readable:    f.Policy.Readable,
			Settable:    settable,
			HasOriginal: f.Policy.Readable || settable,
			Immutable:   f.Policy.ImmutableAfterInsert,
			Sensitive:   f.Policy.Sensitive,
			IsSlice:     isSlice,
		})
		imports = append(imports, f.GoType.Import)
	}
	data.Imports = uniqueSortedImports(imports...)

	for _, rel := range m.Relations {
		cacheField, loadedField := relationCacheField(rel.Name)
		cacheType := "*" + rel.Target.Row
		if rel.Kind == config.HasMany || rel.Kind == config.ManyToMany {
			cacheType = "[]*" + rel.Target.Row
		}
		data.RelationCaches = append(data.RelationCaches, relationCacheFieldData{
			CacheField:  cacheField,
			CacheType:   cacheType,
			LoadedField: loadedField,
		})
	}

	filePath := fmt.Sprintf("%s/%s_gen.go", ctx.Directory, fileStem(m.Row))
	return render(filePath, "model_gen.go", modelTemplate, data, ctx.Name, m.Name)
}
