package codegen

import (
	"fmt"
	"sort"
	"strings"

	"github.com/macoaure/sqlc-model/internal/diagnostics"
	"github.com/macoaure/sqlc-model/internal/plan"
)

const recordTemplate = `// Code generated by sqlc-model. DO NOT EDIT.
package {{.Package}}
{{if .Imports}}
import (
{{- range .Imports}}
	"{{.}}"
{{- end}}
)
{{end}}
// {{.RecordType}} is {{.Row}}'s generated current/original value shape, one
// field per column returned by its canonical (insert) query, in that query's
// column order.
type {{.RecordType}} struct {
{{- range .Fields}}
	{{.GoField}} {{.GoType}}
{{- end}}
}
`

type recordFieldData struct {
	GoField string
	GoType  string
}

type recordTemplateData struct {
	Package    string
	Imports    []string
	Row        string
	RecordType string
	Fields     []recordFieldData
}

// RecordTypeName is the unexported record struct name for a model, e.g.
// "userRecord" for a model whose Row is "User".
func RecordTypeName(row string) string {
	return strings.ToLower(row[:1]) + row[1:] + "Record"
}

// StoreTypeName is the unexported store struct name for a model, e.g.
// "userStore" for a model whose Row is "User".
func StoreTypeName(row string) string {
	return strings.ToLower(row[:1]) + row[1:] + "Store"
}

// fileStem is the shared filename stem for a model's generated files, e.g.
// "user" for a model whose Row is "User".
func fileStem(row string) string {
	return strings.ToLower(row)
}

// uniqueSortedImports dedupes and sorts import paths, dropping empty
// entries (GoType.Import is "" for types needing no extra import).
func uniqueSortedImports(paths ...string) []string {
	seen := make(map[string]bool, len(paths))
	var out []string
	for _, p := range paths {
		if p == "" || seen[p] {
			continue
		}
		seen[p] = true
		out = append(out, p)
	}
	sort.Strings(out)
	return out
}

// RenderRecord renders <model>_record_gen.go: the internal record shape the
// model's store adapter scans query results into (plan.md's "internal
// store/record adapters"). Generated as an unexported type in the context
// package itself, not a nested internal/<model> package, because this
// plugin has no way to know the consuming project's own Go module path for
// a nested package's import statement — see internal/codegen/store.go for
// the same reasoning applied to the store adapter.
func RenderRecord(ctx plan.ResolvedContext, m plan.ResolvedModel) ([]byte, []diagnostics.Diagnostic) {
	data := recordTemplateData{Package: ctx.Package, Row: m.Row, RecordType: RecordTypeName(m.Row)}
	var imports []string
	for _, f := range m.Fields {
		data.Fields = append(data.Fields, recordFieldData{GoField: f.GoField, GoType: f.GoType.Expr})
		imports = append(imports, f.GoType.Import)
	}
	data.Imports = uniqueSortedImports(imports...)
	filePath := fmt.Sprintf("%s/%s_record_gen.go", ctx.Directory, fileStem(m.Row))
	return render(filePath, "record_gen.go", recordTemplate, data, ctx.Name, m.Name)
}
