package codegen

import (
	"encoding/json"
	"fmt"
	"strconv"

	"github.com/macoaure/sqlc-gen-richmodel/internal/config"
	"github.com/macoaure/sqlc-gen-richmodel/internal/diagnostics"
	"github.com/macoaure/sqlc-gen-richmodel/internal/mapping"
	"github.com/macoaure/sqlc-gen-richmodel/internal/plan"
)

const relationTemplate = `// Code generated by sqlc-gen-richmodel. DO NOT EDIT.
package {{.Package}}

import (
	"context"
	"errors"
	"log"

	"github.com/jackc/pgx/v5"
{{- range .Imports}}
	"{{.}}"
{{- end}}
)

// {{.BuilderType}} is a lazy, chainable accessor for {{.ParentRow}}'s
// {{.RelationName}} relation. See contracts/relation-api.md for the full
// contract every generated relation builder satisfies. Builder values are
// immutable by convention: chaining a scope returns a new value and never
// mutates r, the parent model, or another builder value (FR-010).
type {{.BuilderType}} struct {
	parent       *{{.ParentRow}}
	scopeValues  map[string]any
	variantQuery string
}

// {{.RelationName}} returns a new {{.BuilderType}} for u. Constructing it
// performs no data access (FR-012); call Get to read.
func (u *{{.ParentRow}}) {{.RelationName}}() {{.BuilderType}} {
	return {{.BuilderType}}{parent: u}
}

func (r {{.BuilderType}}) isScoped() bool {
	return len(r.scopeValues) > 0 || r.variantQuery != ""
}

func (r {{.BuilderType}}) exec(ctx context.Context) ({{.ReturnType}}, error) {
	sqlText := {{.LazySQL}}
{{- range .Variants}}
	if r.variantQuery == "{{.Name}}" {
		sqlText = {{.SQL}}
	}
{{- end}}
{{if .ToMany}}
	rows, err := r.parent.coll.session.executor.Query(ctx, sqlText{{range .LazyArgs}}, {{.}}{{end}})
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []*{{.TargetRow}}
	for rows.Next() {
		var rec {{.TargetRecordType}}
		if err := rows.Scan({{range $i, $f := .LazyScan}}{{if $i}}, {{end}}&rec.{{$f}}{{end}}); err != nil {
			return nil, err
		}
		t := &{{.TargetRow}}{coll: r.parent.coll.session.{{.TargetCollectionField}}, state: modelStatePersisted}
		t.current, t.original = rec, rec
{{- if .HasInverse}}
{{- if .InverseToMany}}
		t.{{.InverseCacheField}} = append(t.{{.InverseCacheField}}, r.parent)
{{- else}}
		t.{{.InverseCacheField}} = r.parent
{{- end}}
		t.{{.InverseLoadedField}} = true
{{- end}}
		out = append(out, t)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return out, nil
{{- else}}
row := r.parent.coll.session.executor.QueryRow(ctx, sqlText{{range .LazyArgs}}, {{.}}{{end}})
	var rec {{.TargetRecordType}}
	if err := row.Scan({{range $i, $f := .LazyScan}}{{if $i}}, {{end}}&rec.{{$f}}{{end}}); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, nil
		}
		return nil, err
	}
	t := &{{.TargetRow}}{coll: r.parent.coll.session.{{.TargetCollectionField}}, state: modelStatePersisted}
	t.current, t.original = rec, rec
{{- if .HasInverse}}
{{- if .InverseToMany}}
	t.{{.InverseCacheField}} = append(t.{{.InverseCacheField}}, r.parent)
{{- else}}
	t.{{.InverseCacheField}} = r.parent
{{- end}}
	t.{{.InverseLoadedField}} = true
{{- end}}
	return t, nil
{{- end}}
}

// Get executes {{.RelationName}}'s lazy query on cache miss for an unscoped
// call, or returns the cached value if already loaded (FR-012, FR-016). A
// scoped call always performs its own data access and never touches the
// canonical cache (FR-019).
func (r {{.BuilderType}}) Get(ctx context.Context) ({{.ReturnType}}, error) {
	if !r.isScoped() {
		if r.parent.{{.LoadedField}} {
			return r.parent.{{.CacheField}}, nil
		}
{{- if .HasSession}}
		switch r.parent.coll.session.lazyLoading {
		case LazyLoadingPrevented:
			return nil, ErrLazyLoadingPrevented
		case LazyLoadingLogged:
			log.Printf("richmodel: uncached lazy load of {{.ParentRow}}.{{.RelationName}}")
		}
{{- end}}
	}
	result, err := r.exec(ctx)
	if err != nil {
		return nil, err
	}
	if !r.isScoped() {
		r.parent.{{.CacheField}} = result
		r.parent.{{.LoadedField}} = true
	}
	return result, nil
}

// Reload clears {{.RelationName}}'s canonical cache and performs a fresh
// read unconditionally.
func (r {{.BuilderType}}) Reload(ctx context.Context) ({{.ReturnType}}, error) {
	result, err := r.exec(ctx)
	if err != nil {
		return nil, err
	}
	if !r.isScoped() {
		r.parent.{{.CacheField}} = result
		r.parent.{{.LoadedField}} = true
	}
	return result, nil
}

// Cached returns {{.RelationName}}'s canonical cached value without
// performing any data access (FR-016).
func (r {{.BuilderType}}) Cached() ({{.ReturnType}}, bool) {
	return r.parent.{{.CacheField}}, r.parent.{{.LoadedField}}
}

// Loaded reports whether {{.RelationName}}'s canonical value is already
// loaded, without performing any data access (FR-016).
func (r {{.BuilderType}}) Loaded() bool {
	return r.parent.{{.LoadedField}}
}

// Forget clears {{.RelationName}}'s canonical cache without performing any
// data access (FR-018).
func (r {{.BuilderType}}) Forget() *{{.ParentRow}} {
	r.parent.{{.CacheField}} = nil
	r.parent.{{.LoadedField}} = false
	return r.parent
}
{{if .HasNew}}
// New constructs a new, session-attached, not-yet-persisted {{.TargetRow}}
{{- if .ForeignKeyGoField}}, with {{.RelationName}}'s foreign key pre-assigned{{end}}. It does not persist the child.
func (r {{.BuilderType}}) New() *{{.TargetRow}} {
	t := &{{.TargetRow}}{coll: r.parent.coll.session.{{.TargetCollectionField}}, state: modelStateNew}
{{- if .ForeignKeyGoField}}
	t.current.{{.ForeignKeyGoField}} = r.parent.current.{{.LocalKeyGoField}}
{{- end}}
	return t
}
{{end}}
{{if .IsToOneKind}}
// Associate assigns target as {{.ParentRow}}'s {{.RelationName}}, in
// memory only (call Save to persist). Rejects target if it belongs to a
// different session or has no persisted identifier (FR-021).
func (r {{.BuilderType}}) Associate(target *{{.TargetRow}}) error {
	if target.IsNew() {
		return ErrUnsavedRelated
	}
	if r.parent.coll == nil || target.coll == nil || !sameSessionIdentity(r.parent.coll.session, target.coll.session) {
		return ErrSessionMismatch
	}
	r.parent.current.{{.LocalKeyGoField}} = target.current.{{.ForeignKeyGoField}}
	r.parent.{{.CacheField}} = target
	r.parent.{{.LoadedField}} = true
	return nil
}
{{if .Nullable}}
// Dissociate clears {{.ParentRow}}'s {{.RelationName}} link, in memory
// only (call Save to persist). Generated only because this relation is
// nullable (FR-007).
func (r {{.BuilderType}}) Dissociate() *{{.ParentRow}} {
	var zero {{.LocalKeyGoType}}
	r.parent.current.{{.LocalKeyGoField}} = zero
	r.parent.{{.CacheField}} = nil
	r.parent.{{.LoadedField}} = false
	return r.parent
}
{{end}}
{{end}}
{{if .HasAttach}}
// Attach adds targets to {{.ParentRow}}'s {{.RelationName}} pivot,
// rejecting any target from a different session or with no persisted
// identifier (FR-008, FR-021).
func (r {{.BuilderType}}) Attach(ctx context.Context, targets ...*{{.TargetRow}}) error {
	for _, t := range targets {
		if t.IsNew() {
			return ErrUnsavedRelated
		}
		if r.parent.coll == nil || t.coll == nil || !sameSessionIdentity(r.parent.coll.session, t.coll.session) {
			return ErrSessionMismatch
		}
	}
	for _, t := range targets {
		if _, err := r.parent.coll.session.executor.Exec(ctx, {{.AttachSQL}}, r.parent.current.{{.LocalKeyGoField}}, t.current.{{.TargetKeyGoField}}); err != nil {
			return err
		}
	}
	return nil
}
{{end}}
{{if .HasDetach}}
// Detach removes targets from {{.ParentRow}}'s {{.RelationName}} pivot
// (FR-008).
func (r {{.BuilderType}}) Detach(ctx context.Context, targets ...*{{.TargetRow}}) error {
	for _, t := range targets {
		if _, err := r.parent.coll.session.executor.Exec(ctx, {{.DetachSQL}}, r.parent.current.{{.LocalKeyGoField}}, t.current.{{.TargetKeyGoField}}); err != nil {
			return err
		}
	}
	return nil
}
{{end}}
{{if .HasSync}}
// Sync makes {{.ParentRow}}'s {{.RelationName}} pivot match targets
// exactly: detaching what's no longer desired, attaching what's newly
// desired (FR-008). Sequential list-then-diff-then-attach/detach calls,
// not wrapped in an explicit transaction (research.md — Session.Transaction
// does not exist until spec 003).
func (r {{.BuilderType}}) Sync(ctx context.Context, targets ...*{{.TargetRow}}) error {
	for _, t := range targets {
		if t.IsNew() {
			return ErrUnsavedRelated
		}
		if r.parent.coll == nil || t.coll == nil || !sameSessionIdentity(r.parent.coll.session, t.coll.session) {
			return ErrSessionMismatch
		}
	}

	rows, err := r.parent.coll.session.executor.Query(ctx, {{.SyncListSQL}}, r.parent.current.{{.LocalKeyGoField}})
	if err != nil {
		return err
	}
	current := make(map[{{.TargetKeyGoType}}]bool)
	for rows.Next() {
		var id {{.TargetKeyGoType}}
		if err := rows.Scan(&id); err != nil {
			rows.Close()
			return err
		}
		current[id] = true
	}
	if err := rows.Err(); err != nil {
		rows.Close()
		return err
	}
	rows.Close()

	desired := make(map[{{.TargetKeyGoType}}]bool, len(targets))
	for _, t := range targets {
		desired[t.current.{{.TargetKeyGoField}}] = true
	}

	for id := range current {
		if !desired[id] {
			if _, err := r.parent.coll.session.executor.Exec(ctx, {{.SyncDetachSQL}}, r.parent.current.{{.LocalKeyGoField}}, id); err != nil {
				return err
			}
		}
	}
	for id := range desired {
		if !current[id] {
			if _, err := r.parent.coll.session.executor.Exec(ctx, {{.SyncAttachSQL}}, r.parent.current.{{.LocalKeyGoField}}, id); err != nil {
				return err
			}
		}
	}
	return nil
}
{{end}}
{{range .Scopes}}
{{if eq .Form "value"}}
// {{.Name}} chains a fixed-value scope onto {{$.BuilderType}} (FR-009);
// does not mutate r or the parent model (FR-010).
func (r {{$.BuilderType}}) {{.Name}}() {{$.BuilderType}} {
	r2 := r
	r2.scopeValues = cloneScopeValues(r.scopeValues)
	r2.scopeValues["{{.ParamName}}"] = {{.ValueLiteral}}
	return r2
}
{{else if eq .Form "argument"}}
// {{.Name}} chains a developer-supplied-value scope onto {{$.BuilderType}}
// (FR-009); does not mutate r or the parent model (FR-010).
func (r {{$.BuilderType}}) {{.Name}}(value {{.ArgType}}) {{$.BuilderType}} {
	r2 := r
	r2.scopeValues = cloneScopeValues(r.scopeValues)
	r2.scopeValues["{{.ParamName}}"] = value
	return r2
}
{{else}}
// {{.Name}} chains a query-variant scope onto {{$.BuilderType}}, selecting
// a different configured query for the next terminal read (FR-009); does
// not mutate r or the parent model (FR-010).
func (r {{$.BuilderType}}) {{.Name}}() {{$.BuilderType}} {
	r2 := r
	r2.variantQuery = "{{.Name}}"
	return r2
}
{{end}}
{{end}}
`

type relationVariantData struct {
	Name string
	SQL  string
}

type relationScopeData struct {
	Form         string // "value" | "argument" | "query"
	Name         string
	ParamName    string
	ValueLiteral string
	ArgType      string
}

type relationTemplateData struct {
	Package               string
	ParentRow             string
	RelationName          string
	BuilderType           string
	TargetRow             string
	TargetRecordType      string
	TargetCollectionField string
	ReturnType            string
	ToMany                bool
	IsToOneKind           bool
	Nullable              bool
	CacheField            string
	LoadedField           string
	LazySQL               string
	LazyArgs              []string
	LazyScan              []string
	Variants              []relationVariantData
	HasSession            bool
	HasNew                bool
	ForeignKeyGoField     string
	LocalKeyGoField       string
	LocalKeyGoType        string
	HasAttach             bool
	HasDetach             bool
	HasSync               bool
	AttachSQL             string
	DetachSQL             string
	SyncListSQL           string
	SyncAttachSQL         string
	SyncDetachSQL         string
	TargetKeyGoField      string
	TargetKeyGoType       string
	Scopes                []relationScopeData
	HasInverse            bool
	InverseToMany         bool
	InverseCacheField     string
	InverseLoadedField    string
	Imports               []string
}

// RenderRelation renders <model>_<relation>_relation_gen.go: the lazy
// relation builder for one relation, per contracts/relation-api.md.
func RenderRelation(ctx plan.ResolvedContext, m plan.ResolvedModel, rel plan.ResolvedRelation) ([]byte, []diagnostics.Diagnostic) {
	toMany := rel.Kind == config.HasMany || rel.Kind == config.ManyToMany
	isToOneKind := rel.Kind == config.BelongsTo || rel.Kind == config.HasOne

	cacheField, loadedField := relationCacheField(rel.Name)

	data := relationTemplateData{
		Package:               ctx.Package,
		ParentRow:             m.Row,
		RelationName:          rel.Name,
		BuilderType:           fmt.Sprintf("%s%sRelation", m.Row, rel.Name),
		TargetRow:             rel.Target.Row,
		TargetRecordType:      RecordTypeName(rel.Target.Row),
		TargetCollectionField: CollectionFieldName(rel.Target.Row),
		ReturnType:            "*" + rel.Target.Row,
		ToMany:                toMany,
		IsToOneKind:           isToOneKind,
		Nullable:              rel.Nullable,
		CacheField:            cacheField,
		LoadedField:           loadedField,
		HasSession:            true,
		HasNew:                rel.Kind == config.HasMany || rel.Kind == config.HasOne || rel.Kind == config.ManyToMany,
	}
	if toMany {
		data.ReturnType = "[]*" + rel.Target.Row
	}

	var extraImports []string
	if rel.LocalKey != nil {
		data.LocalKeyGoField = rel.LocalKey.GoField
		data.LocalKeyGoType = rel.LocalKey.GoType.Expr
		extraImports = append(extraImports, rel.LocalKey.GoType.Import)
	}
	if rel.ForeignKeyField != nil {
		data.ForeignKeyGoField = rel.ForeignKeyField.GoField
	}
	if rel.TargetKey != nil {
		data.TargetKeyGoField = rel.TargetKey.GoField
		data.TargetKeyGoType = rel.TargetKey.GoType.Expr
		extraImports = append(extraImports, rel.TargetKey.GoType.Import)
	}

	if rel.Inverse != nil {
		data.HasInverse = true
		data.InverseToMany = rel.Inverse.Kind == config.HasMany || rel.Inverse.Kind == config.ManyToMany
		invCache, invLoaded := relationCacheField(rel.Inverse.Name)
		data.InverseCacheField = invCache
		data.InverseLoadedField = invLoaded
	}

	if rel.LazyQuery != nil {
		data.LazySQL = strconv.Quote(rel.LazyQuery.GetText())
		for _, p := range sortedRelationParams(rel.LazyParams) {
			data.LazyArgs = append(data.LazyArgs, relationParamExpr(p))
		}
		for _, f := range rel.LazyScan {
			data.LazyScan = append(data.LazyScan, f.GoField)
		}
	}

	if rel.AttachQuery != nil {
		data.HasAttach = true
		data.AttachSQL = strconv.Quote(rel.AttachQuery.GetText())
	}
	if rel.DetachQuery != nil {
		data.HasDetach = true
		data.DetachSQL = strconv.Quote(rel.DetachQuery.GetText())
	}
	if rel.SyncList != nil && rel.SyncAttach != nil && rel.SyncDetach != nil {
		data.HasSync = true
		data.SyncListSQL = strconv.Quote(rel.SyncList.GetText())
		data.SyncAttachSQL = strconv.Quote(rel.SyncAttach.GetText())
		data.SyncDetachSQL = strconv.Quote(rel.SyncDetach.GetText())
	}

	var scopeDiags []diagnostics.Diagnostic
	for _, sc := range rel.Scopes {
		switch {
		case sc.Query != "":
			data.Scopes = append(data.Scopes, relationScopeData{Form: "query", Name: sc.Name})
			if variant := rel.ScopeVariantQueries[sc.Name]; variant != nil {
				data.Variants = append(data.Variants, relationVariantData{Name: sc.Name, SQL: strconv.Quote(variant.GetText())})
			}
		case sc.Argument != "":
			data.Scopes = append(data.Scopes, relationScopeData{Form: "argument", Name: sc.Name, ParamName: sc.Parameter, ArgType: sc.Argument})
			extraImports = append(extraImports, paramGoTypeForScope(rel, sc.Name).Import)
		default:
			gt := paramGoTypeForScope(rel, sc.Name)
			lit, err := goLiteral(sc.Value, gt)
			if err != nil {
				scopeDiags = append(scopeDiags, diagnostics.Diagnostic{
					Severity: diagnostics.SeverityError,
					Path:     fmt.Sprintf("%s/%s_%s_relation_gen.go", ctx.Directory, fileStem(m.Row), fileStem(rel.Name)),
					Context:  ctx.Name,
					Model:    m.Name,
					Relation: rel.Name,
					Message:  fmt.Sprintf("scope %q: %v", sc.Name, err),
				})
				continue
			}
			data.Scopes = append(data.Scopes, relationScopeData{Form: "value", Name: sc.Name, ParamName: sc.Parameter, ValueLiteral: lit})
		}
	}
	if len(scopeDiags) > 0 {
		return nil, scopeDiags
	}
	data.Imports = uniqueSortedImports(extraImports...)

	filePath := fmt.Sprintf("%s/%s_%s_relation_gen.go", ctx.Directory, fileStem(m.Row), fileStem(rel.Name))
	return render(filePath, "relation_gen.go", relationTemplate, data, ctx.Name, m.Name)
}

// paramGoTypeForScope finds the resolved Go type of the query parameter
// scopeName's ScopeConfiguration binds — joined via the LazyParam whose
// ScopeName matches (set by resolveLazyParams from a "scope.<Name>" source
// binding), not by the query parameter's own name, since a scope's own
// name and the parameter name it maps to are configured independently.
func paramGoTypeForScope(rel plan.ResolvedRelation, scopeName string) mapping.GoType {
	for _, p := range rel.LazyParams {
		if p.Source == plan.ParamFromScope && p.ScopeName == scopeName {
			return p.GoType
		}
	}
	return mapping.GoType{Expr: "string"}
}

func relationParamExpr(p plan.RelationParam) string {
	if p.Source == plan.ParamFromParent {
		return fmt.Sprintf("r.parent.current.%s", p.ParentField.GoField)
	}
	def := "nil"
	if len(p.Default) > 0 {
		if lit, err := goLiteral(p.Default, p.GoType); err == nil {
			def = lit
		}
	}
	// Keyed by the query parameter's own name (p.Name), matching exactly
	// what a scope method writes via scopeValues["<parameter name>"] = ...
	// (ParamName on relationScopeData is the same config field: sc.Parameter).
	return fmt.Sprintf("relationScopeArg(r.scopeValues, %q, %s)", p.Name, def)
}

func sortedRelationParams(params []plan.RelationParam) []plan.RelationParam {
	out := make([]plan.RelationParam, len(params))
	copy(out, params)
	for i := 1; i < len(out); i++ {
		for j := i; j > 0 && out[j].Number < out[j-1].Number; j-- {
			out[j], out[j-1] = out[j-1], out[j]
		}
	}
	return out
}

// goLiteral renders a JSON default/fixed-scope value as a Go source
// literal compatible with gt. Unsupported shapes (arrays, objects) return
// an error surfaced as a generation diagnostic rather than emitting
// invalid Go source.
func goLiteral(raw json.RawMessage, gt mapping.GoType) (string, error) {
	if len(raw) == 0 {
		return "nil", nil
	}
	var v any
	if err := json.Unmarshal(raw, &v); err != nil {
		return "", err
	}
	switch val := v.(type) {
	case nil:
		return "nil", nil
	case bool:
		return strconv.FormatBool(val), nil
	case float64:
		switch gt.Expr {
		case "int16", "int32", "int64":
			return strconv.FormatInt(int64(val), 10), nil
		case "float32", "float64":
			return strconv.FormatFloat(val, 'g', -1, 64), nil
		default:
			return strconv.FormatInt(int64(val), 10), nil
		}
	case string:
		return strconv.Quote(val), nil
	default:
		return "", fmt.Errorf("unsupported literal value type %T", val)
	}
}
