package codegen

import (
	"fmt"

	"github.com/macoaure/sqlc-model/internal/diagnostics"
	"github.com/macoaure/sqlc-model/internal/plan"
)

const sessionTemplate = `// Code generated by sqlc-model. DO NOT EDIT.
package {{.Package}}

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgxpool"
)

type richmodelExecutor interface {
	Exec(context.Context, string, ...any) (pgconn.CommandTag, error)
	Query(context.Context, string, ...any) (pgx.Rows, error)
	QueryRow(context.Context, string, ...any) pgx.Row
}

type sessionIdentity struct{}

// Session owns the database connection pool and one collection per
// configured model in this context.
type Session struct {
	pool     *pgxpool.Pool
	executor richmodelExecutor
	identity *sessionIdentity
{{- if .HasRelations}}
	lazyLoading LazyLoadingMode
{{- end}}
{{- range .Models}}
	{{.CollectionField}} *{{.Row}}Collection
{{- end}}
}
{{if .HasRelations}}
// SessionOption configures optional Session behavior at construction time.
type SessionOption func(*Session)

// LazyLoadingMode controls whether an uncached lazy relation read is
// allowed, logged, or prevented (FR-020; contracts/relation-api.md).
type LazyLoadingMode uint8

const (
	// LazyLoadingAllowed performs uncached lazy reads normally (default).
	LazyLoadingAllowed LazyLoadingMode = iota
	// LazyLoadingLogged performs uncached lazy reads but reports them via
	// the session's configured Logger, if any.
	LazyLoadingLogged
	// LazyLoadingPrevented rejects an uncached lazy read with
	// ErrLazyLoadingPrevented instead of performing it. Reads of an
	// already-loaded or eager-loaded relation are unaffected.
	LazyLoadingPrevented
)

// WithLazyLoading sets mode as the session's lazy-loading policy.
func WithLazyLoading(mode LazyLoadingMode) SessionOption {
	return func(s *Session) { s.lazyLoading = mode }
}
{{end}}
// New creates a Session backed by pool, with every context model's
// collection attached.
func New(pool *pgxpool.Pool{{if .HasRelations}}, opts ...SessionOption{{end}}) *Session {
	s := &Session{pool: pool, executor: pool, identity: &sessionIdentity{}}
{{- if .HasRelations}}
	for _, opt := range opts {
		opt(s)
	}
{{- end}}
	s.initCollections()
	return s
}

func (s *Session) initCollections() {
{{- range .Models}}
	s.{{.CollectionField}} = new{{.Row}}Collection(s)
{{- end}}
}

// Transaction runs fn inside one database transaction. fn receives a fresh
// transaction-scoped session; returning nil commits, returning an error
// rolls back and returns that error, and panicking rolls back before the
// panic continues.
func (s *Session) Transaction(ctx context.Context, fn func(*Session) error) error {
	if s.pool == nil {
		return ErrTransactionUnavailable
	}
	tx, err := s.pool.Begin(ctx)
	if err != nil {
		return err
	}

	txSession := &Session{executor: tx, identity: &sessionIdentity{}{{if .HasRelations}}, lazyLoading: s.lazyLoading{{end}}}
	txSession.initCollections()

	closed := false
	defer func() {
		if !closed {
			_ = tx.Rollback(ctx)
		}
	}()

	if err := fn(txSession); err != nil {
		_ = tx.Rollback(ctx)
		closed = true
		return err
	}
	if err := tx.Commit(ctx); err != nil {
		closed = true
		return err
	}
	closed = true
	return nil
}

func sameSessionIdentity(a, b *Session) bool {
	return a != nil && b != nil && a.identity == b.identity
}

// modelState is a generated model's lifecycle state (contracts/
// generated-model-api.md's "Lifecycle-state queries").
type modelState uint8

const (
	modelStateNew modelState = iota
	modelStatePersisted
	modelStateDeleted
)

// Sentinel lifecycle errors returned by every generated model's terminal methods.
var (
	// ErrModelDeleted is returned by Save/Refresh on a deleted model.
	ErrModelDeleted = errors.New("richmodel: model is deleted")
	// ErrModelDetached is returned by Save/Delete/Refresh/lazy-load on a
	// model with no owning session.
	ErrModelDetached = errors.New("richmodel: model is not attached to a session")
	// ErrModelNotPersisted is returned by operations that require a
	// persisted backing row on a new model.
	ErrModelNotPersisted = errors.New("richmodel: model is not persisted")
	// ErrInvalidModelState is returned when generated model state is
	// internally inconsistent.
	ErrInvalidModelState = errors.New("richmodel: invalid model state")
	// ErrUnsupportedQueryContract is returned when a generated method has
	// no compatible configured sqlc query contract.
	ErrUnsupportedQueryContract = errors.New("richmodel: unsupported query contract")
	// ErrDeletedModel is kept for compatibility; use ErrModelDeleted.
	ErrDeletedModel = ErrModelDeleted
	// ErrDetachedModel is kept for compatibility; use ErrModelDetached.
	ErrDetachedModel = ErrModelDetached
	// ErrImmutableField is recorded as a field-level error when a setter
	// for an immutable_after_insert field is called on a persisted model.
	ErrImmutableField = errors.New("richmodel: field is immutable after insert")
	// ErrOperationNotConfigured is returned by Save/Delete/Refresh when the
	// underlying lifecycle operation they need has no configured query.
	ErrOperationNotConfigured = errors.New("richmodel: operation has no configured query")
	// ErrTransactionUnavailable is returned when Transaction is called on a
	// session that cannot open a new database transaction.
	ErrTransactionUnavailable = errors.New("richmodel: transaction is unavailable on this session")
	// ErrNotFound is returned by single-record fetches when no row matches.
	ErrNotFound = errors.New("richmodel: not found")
{{- if .HasRelations}}
	// ErrSessionMismatch is returned by Associate/Attach/Sync when the
	// related model belongs to a different session than the parent.
	ErrSessionMismatch = errors.New("richmodel: related model belongs to a different session")
	// ErrUnsavedRelatedModel is returned by Associate/Attach/Sync when the
	// related model has no persisted identifier (IsNew()).
	ErrUnsavedRelatedModel = errors.New("richmodel: related model has no persisted identifier")
	// ErrUnsavedRelated is kept for compatibility; use ErrUnsavedRelatedModel.
	ErrUnsavedRelated = ErrUnsavedRelatedModel
	// ErrLazyLoadingPrevented is returned by a relation's Get/Reload when
	// the session's LazyLoadingMode is LazyLoadingPrevented and the
	// relation is not already cached or eager-loaded.
	ErrLazyLoadingPrevented = errors.New("richmodel: lazy loading of an uncached relation is prevented")
{{- end}}
)

// DatabaseErrorKind classifies PostgreSQL/pgx errors returned by generated
// persistence methods.
type DatabaseErrorKind uint8

const (
	DatabaseErrorUnknown DatabaseErrorKind = iota
	DatabaseErrorUniqueViolation
	DatabaseErrorForeignKeyViolation
	DatabaseErrorNotNullViolation
	DatabaseErrorCheckViolation
	DatabaseErrorSerializationFailure
	DatabaseErrorDeadlock
)

// DatabaseError wraps a driver error while preserving its cause.
type DatabaseError struct {
	Kind DatabaseErrorKind
	Err error
}

func (e *DatabaseError) Error() string {
	if e == nil || e.Err == nil {
		return "richmodel: database error"
	}
	return e.Err.Error()
}

func (e *DatabaseError) Unwrap() error {
	if e == nil {
		return nil
	}
	return e.Err
}

func classifyDatabaseError(err error) error {
	if err == nil {
		return nil
	}
	var pgErr *pgconn.PgError
	if !errors.As(err, &pgErr) {
		return &DatabaseError{Kind: DatabaseErrorUnknown, Err: err}
	}
	return &DatabaseError{Kind: databaseErrorKind(pgErr.Code), Err: err}
}

func databaseErrorKind(code string) DatabaseErrorKind {
	switch code {
	case "23505":
		return DatabaseErrorUniqueViolation
	case "23503":
		return DatabaseErrorForeignKeyViolation
	case "23502":
		return DatabaseErrorNotNullViolation
	case "23514":
		return DatabaseErrorCheckViolation
	case "40001":
		return DatabaseErrorSerializationFailure
	case "40P01":
		return DatabaseErrorDeadlock
	default:
		return DatabaseErrorUnknown
	}
}

// ValidationError identifies one current field-level validation failure.
type ValidationError struct {
	Model string
	Field string
	Err error
}

func (e ValidationError) Error() string {
	if e.Err == nil {
		return e.Model + "." + e.Field
	}
	return e.Model + "." + e.Field + ": " + e.Err.Error()
}

func (e ValidationError) Unwrap() error {
	return e.Err
}
{{if .HasRelations}}
// cloneScopeValues copies src so a relation builder's scope methods can
// chain new values without mutating the receiver or any other builder
// value already in hand (FR-010).
func cloneScopeValues(src map[string]any) map[string]any {
	dst := make(map[string]any, len(src)+1)
	for k, v := range src {
		dst[k] = v
	}
	return dst
}

// relationScopeArg resolves a scope-bound query parameter's value: whatever
// a chained scope set, or def when no scope in the chain set it.
func relationScopeArg(values map[string]any, key string, def any) any {
	if v, ok := values[key]; ok {
		return v
	}
	return def
}
{{end}}
`

type sessionModelData struct {
	Row             string
	CollectionField string
}

type sessionTemplateData struct {
	Package      string
	Models       []sessionModelData
	HasRelations bool
}

// CollectionFieldName is the exported Session field name for a model's
// collection, e.g. "Users" for a model named "User" (naive English
// pluralization: append "s"; irregular plurals are not special-cased).
func CollectionFieldName(row string) string {
	return row + "s"
}

// RenderSession renders session_gen.go for one context (one per context,
// contracts/generated-model-api.md and quickstart.md's `content.New(pool)`).
func RenderSession(ctx plan.ResolvedContext) ([]byte, []diagnostics.Diagnostic) {
	data := sessionTemplateData{Package: ctx.Package}
	for _, m := range ctx.Models {
		data.Models = append(data.Models, sessionModelData{Row: m.Row, CollectionField: CollectionFieldName(m.Row)})
		if len(m.Relations) > 0 {
			data.HasRelations = true
		}
	}
	filePath := fmt.Sprintf("%s/session_gen.go", ctx.Directory)
	return render(filePath, "session_gen.go", sessionTemplate, data, ctx.Name, "")
}
