package codegen

import (
	"fmt"

	"github.com/macoaure/sqlc-gen-richmodel/internal/diagnostics"
	"github.com/macoaure/sqlc-gen-richmodel/internal/plan"
)

const sessionTemplate = `// Code generated by sqlc-gen-richmodel. DO NOT EDIT.
package {{.Package}}

import (
	"errors"

	"github.com/jackc/pgx/v5/pgxpool"
)

// Session owns the database connection pool and one collection per
// configured model in this context.
type Session struct {
	pool *pgxpool.Pool
{{- range .Models}}
	{{.CollectionField}} *{{.Row}}Collection
{{- end}}
}

// New creates a Session backed by pool, with every context model's
// collection attached.
func New(pool *pgxpool.Pool) *Session {
	s := &Session{pool: pool}
{{- range .Models}}
	s.{{.CollectionField}} = new{{.Row}}Collection(s, pool)
{{- end}}
	return s
}

// modelState is a generated model's lifecycle state (contracts/
// generated-model-api.md's "Lifecycle-state queries").
type modelState uint8

const (
	modelStateNew modelState = iota
	modelStatePersisted
	modelStateDeleted
)

// Sentinel errors returned by every generated model's terminal methods.
var (
	// ErrDeletedModel is returned by Save/Refresh on a deleted model.
	ErrDeletedModel = errors.New("richmodel: model is deleted")
	// ErrDetachedModel is returned by Save/Delete/Refresh on a model with
	// no owning session.
	ErrDetachedModel = errors.New("richmodel: model is not attached to a session")
	// ErrImmutableField is recorded as a field-level error when a setter
	// for an immutable_after_insert field is called on a persisted model.
	ErrImmutableField = errors.New("richmodel: field is immutable after insert")
	// ErrOperationNotConfigured is returned by Save/Delete/Refresh when the
	// underlying lifecycle operation they need has no configured query.
	ErrOperationNotConfigured = errors.New("richmodel: operation has no configured query")
)
`

type sessionModelData struct {
	Row             string
	CollectionField string
}

type sessionTemplateData struct {
	Package string
	Models  []sessionModelData
}

// CollectionFieldName is the exported Session field name for a model's
// collection, e.g. "Users" for a model named "User" (naive English
// pluralization: append "s"; irregular plurals are not special-cased).
func CollectionFieldName(row string) string {
	return row + "s"
}

// RenderSession renders session_gen.go for one context (one per context,
// contracts/generated-model-api.md and quickstart.md's `content.New(pool)`).
func RenderSession(ctx plan.ResolvedContext) ([]byte, []diagnostics.Diagnostic) {
	data := sessionTemplateData{Package: ctx.Package}
	for _, m := range ctx.Models {
		data.Models = append(data.Models, sessionModelData{Row: m.Row, CollectionField: CollectionFieldName(m.Row)})
	}
	filePath := fmt.Sprintf("%s/session_gen.go", ctx.Directory)
	return render(filePath, "session_gen.go", sessionTemplate, data, ctx.Name, "")
}
