package codegen

import (
	"fmt"
	"strconv"

	"github.com/macoaure/sqlc-gen-richmodel/internal/contract"
	"github.com/macoaure/sqlc-gen-richmodel/internal/diagnostics"
	"github.com/macoaure/sqlc-gen-richmodel/internal/plan"
)

const storeTemplate = `// Code generated by sqlc-gen-richmodel. DO NOT EDIT.
package {{.Package}}

import (
	"context"
{{- if .NeedsNoRows}}
	"errors"
{{- end}}
{{- if .NeedsFmt}}
	"fmt"
{{- end}}
{{- if .NeedsNoRows}}
	"github.com/jackc/pgx/v5"
{{- end}}
)

// {{.StoreType}} executes {{.Row}}'s configured sqlc queries directly via
// pgx, using each query's already-validated, already-parameterized SQL text
// exactly as sqlc's own generated code would (sqlc-gen-go embeds this same
// query.Text verbatim as its query constant) — the query itself remains
// sqlc's statically-verified output; this adapter only executes it.
type {{.StoreType}} struct {
	executor richmodelExecutor
}

func new{{.Row}}Store(executor richmodelExecutor) *{{.StoreType}} {
	return &{{.StoreType}}{executor: executor}
}
{{range .Operations}}
func (s *{{$.StoreType}}) {{.Method}}(ctx context.Context, rec {{$.RecordType}}) ({{.ReturnType}}, error) {
{{- if .ReturnsRow}}
	var out {{$.RecordType}}
{{- range .Scan}}
{{- if .ValueObject}}
	var {{.ScanVar}} {{.PersistedGoType}}
{{- end}}
{{- end}}
	row := s.executor.QueryRow(ctx, {{.SQL}}{{range .Args}}, {{.}}{{end}})
	if err := row.Scan({{range $i, $f := .Scan}}{{if $i}}, {{end}}{{.ScanTarget}}{{end}}); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return {{$.RecordType}}{}, ErrNotFound
		}
		return {{$.RecordType}}{}, err
	}
{{- range .Scan}}
{{- if .ValueObject}}
	{{.LocalVar}}, err := {{.Constructor}}({{.ScanVar}})
	if err != nil {
		return {{$.RecordType}}{}, fmt.Errorf("{{$.Row}}.{{.GoField}}: %w", err)
	}
	out.{{.GoField}} = {{.LocalVar}}
{{- end}}
{{- end}}
	return out, nil
{{- else}}
	tag, err := s.executor.Exec(ctx, {{.SQL}}{{range .Args}}, {{.}}{{end}})
	if err != nil {
		return 0, err
	}
	return tag.RowsAffected(), nil
{{- end}}
}
{{end}}
`

type storeOperationData struct {
	Method     string
	SQL        string
	Args       []string
	ReturnsRow bool
	ReturnType string
	Scan       []storeScanData
}

type storeScanData struct {
	GoField         string
	ScanTarget      string
	ScanVar         string
	LocalVar        string
	PersistedGoType string
	ValueObject     bool
	Constructor     string
}

type storeTemplateData struct {
	Package     string
	Row         string
	StoreType   string
	RecordType  string
	Operations  []storeOperationData
	NeedsFmt    bool
	NeedsNoRows bool
}

// RenderStore renders <model>_store_gen.go: the adapter that executes m's
// configured sqlc queries. Generated as an unexported type in the context
// package itself rather than a nested internal/<model> package — this
// plugin has no way to know the consuming project's own Go module path
// (needed for a nested package's import statement) at generation time,
// since sqlc-gen-go's own output doesn't exist yet during this invocation
// (contracts/plugin-io.md) and nothing in the plugin request communicates
// the target module path.
func RenderStore(ctx plan.ResolvedContext, m plan.ResolvedModel) ([]byte, []diagnostics.Diagnostic) {
	data := storeTemplateData{
		Package:    ctx.Package,
		Row:        m.Row,
		StoreType:  StoreTypeName(m.Row),
		RecordType: RecordTypeName(m.Row),
	}

	for _, ro := range []*plan.ResolvedOperation{m.Operations.Find, m.Operations.Insert, m.Operations.Update, m.Operations.Delete, m.Operations.Refresh} {
		if ro == nil {
			continue
		}
		op := storeOperationData{
			Method:     string(ro.Kind),
			SQL:        strconv.Quote(ro.Query.GetText()),
			ReturnsRow: ro.Kind != contract.Delete,
		}
		if op.ReturnsRow {
			op.ReturnType = data.RecordType
			data.NeedsNoRows = true
		} else {
			op.ReturnType = "int64"
		}
		for _, pb := range sortedParams(ro.Params) {
			expr := "rec." + pb.Field.GoField
			if pb.Field.ValueObject != nil {
				expr += "." + pb.Field.ValueObject.Accessor + "()"
			}
			op.Args = append(op.Args, expr)
		}
		for _, f := range ro.Scan {
			scan := storeScanData{GoField: f.GoField, ScanTarget: "&out." + f.GoField}
			if f.ValueObject != nil {
				data.NeedsFmt = true
				scan.ValueObject = true
				scan.ScanVar = "scan" + f.GoField
				scan.LocalVar = lowerFirst(f.GoField)
				scan.PersistedGoType = f.PersistedGoType.Expr
				scan.Constructor = f.ValueObject.Constructor
				scan.ScanTarget = "&" + scan.ScanVar
			}
			op.Scan = append(op.Scan, scan)
		}
		data.Operations = append(data.Operations, op)
	}

	filePath := fmt.Sprintf("%s/%s_store_gen.go", ctx.Directory, fileStem(m.Row))
	return render(filePath, "store_gen.go", storeTemplate, data, ctx.Name, m.Name)
}

// sortedParams orders bindings by their query positional Number, since
// plan.Build appends them in the query's declared parameter order already
// but callers of RenderStore shouldn't depend on that going forward.
func sortedParams(params []plan.ParamBinding) []plan.ParamBinding {
	out := make([]plan.ParamBinding, len(params))
	copy(out, params)
	for i := 1; i < len(out); i++ {
		for j := i; j > 0 && out[j].Number < out[j-1].Number; j-- {
			out[j], out[j-1] = out[j-1], out[j]
		}
	}
	return out
}
