// Code generated by sqlc-model. DO NOT EDIT.
package content

// UserField identifies one field of User, in declared field order.
type UserField uint8

const (
	UserFieldID UserField = iota
	UserFieldName
	UserFieldCount
)

// PostField identifies one field of Post, in declared field order.
type PostField uint8

const (
	PostFieldID PostField = iota
	PostFieldUserID
	PostFieldTitle
	PostFieldCount
)

// TagField identifies one field of Tag, in declared field order.
type TagField uint8

const (
	TagFieldID TagField = iota
	TagFieldName
	TagFieldCount
)
