// Code generated by sqlc-gen-richmodel. DO NOT EDIT.
package content

import (
	"context"
	"log"

	"github.com/jackc/pgx/v5/pgtype"
)

// PostTagsRelation is a lazy, chainable accessor for Post's
// Tags relation. See contracts/relation-api.md for the full
// contract every generated relation builder satisfies. Builder values are
// immutable by convention: chaining a scope returns a new value and never
// mutates r, the parent model, or another builder value (FR-010).
type PostTagsRelation struct {
	parent       *Post
	scopeValues  map[string]any
	variantQuery string
}

// Tags returns a new PostTagsRelation for u. Constructing it
// performs no data access (FR-012); call Get to read.
func (u *Post) Tags() PostTagsRelation {
	return PostTagsRelation{parent: u}
}

func (r PostTagsRelation) isScoped() bool {
	return len(r.scopeValues) > 0 || r.variantQuery != ""
}

func (r PostTagsRelation) exec(ctx context.Context) ([]*Tag, error) {
	sqlText := "SELECT tags.id, tags.name FROM tags INNER JOIN post_tags ON post_tags.tag_id = tags.id WHERE post_tags.post_id = $1;"

	rows, err := r.parent.coll.session.executor.Query(ctx, sqlText, r.parent.current.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []*Tag
	for rows.Next() {
		var rec tagRecord
		if err := rows.Scan(&rec.ID, &rec.Name); err != nil {
			return nil, err
		}
		t := &Tag{coll: r.parent.coll.session.Tags, state: modelStatePersisted}
		t.current, t.original = rec, rec
		out = append(out, t)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return out, nil
}

// Get executes Tags's lazy query on cache miss for an unscoped
// call, or returns the cached value if already loaded (FR-012, FR-016). A
// scoped call always performs its own data access and never touches the
// canonical cache (FR-019).
func (r PostTagsRelation) Get(ctx context.Context) ([]*Tag, error) {
	if !r.isScoped() {
		if r.parent.tagsLoaded {
			return r.parent.tagsCache, nil
		}
		switch r.parent.coll.session.lazyLoading {
		case LazyLoadingPrevented:
			return nil, ErrLazyLoadingPrevented
		case LazyLoadingLogged:
			log.Printf("richmodel: uncached lazy load of Post.Tags")
		}
	}
	result, err := r.exec(ctx)
	if err != nil {
		return nil, err
	}
	if !r.isScoped() {
		r.parent.tagsCache = result
		r.parent.tagsLoaded = true
	}
	return result, nil
}

// Reload clears Tags's canonical cache and performs a fresh
// read unconditionally.
func (r PostTagsRelation) Reload(ctx context.Context) ([]*Tag, error) {
	result, err := r.exec(ctx)
	if err != nil {
		return nil, err
	}
	if !r.isScoped() {
		r.parent.tagsCache = result
		r.parent.tagsLoaded = true
	}
	return result, nil
}

// Cached returns Tags's canonical cached value without
// performing any data access (FR-016).
func (r PostTagsRelation) Cached() ([]*Tag, bool) {
	return r.parent.tagsCache, r.parent.tagsLoaded
}

// Loaded reports whether Tags's canonical value is already
// loaded, without performing any data access (FR-016).
func (r PostTagsRelation) Loaded() bool {
	return r.parent.tagsLoaded
}

// Forget clears Tags's canonical cache without performing any
// data access (FR-018).
func (r PostTagsRelation) Forget() *Post {
	r.parent.tagsCache = nil
	r.parent.tagsLoaded = false
	return r.parent
}

// New constructs a new, session-attached, not-yet-persisted Tag. It does not persist the child.
func (r PostTagsRelation) New() *Tag {
	t := &Tag{coll: r.parent.coll.session.Tags, state: modelStateNew}
	return t
}

// Attach adds targets to Post's Tags pivot,
// rejecting any target from a different session or with no persisted
// identifier (FR-008, FR-021).
func (r PostTagsRelation) Attach(ctx context.Context, targets ...*Tag) error {
	for _, t := range targets {
		if t.IsNew() {
			return ErrUnsavedRelated
		}
		if r.parent.coll == nil || t.coll == nil || !sameSessionIdentity(r.parent.coll.session, t.coll.session) {
			return ErrSessionMismatch
		}
	}
	for _, t := range targets {
		if _, err := r.parent.coll.session.executor.Exec(ctx, "INSERT INTO post_tags (post_id, tag_id) VALUES ($1, $2);", r.parent.current.ID, t.current.ID); err != nil {
			return err
		}
	}
	return nil
}

// Detach removes targets from Post's Tags pivot
// (FR-008).
func (r PostTagsRelation) Detach(ctx context.Context, targets ...*Tag) error {
	for _, t := range targets {
		if _, err := r.parent.coll.session.executor.Exec(ctx, "DELETE FROM post_tags WHERE post_id = $1 AND tag_id = $2;", r.parent.current.ID, t.current.ID); err != nil {
			return err
		}
	}
	return nil
}

// Sync makes Post's Tags pivot match targets
// exactly: detaching what's no longer desired, attaching what's newly
// desired (FR-008). Sequential list-then-diff-then-attach/detach calls,
// not wrapped in an explicit transaction (research.md — Session.Transaction
// does not exist until spec 003).
func (r PostTagsRelation) Sync(ctx context.Context, targets ...*Tag) error {
	for _, t := range targets {
		if t.IsNew() {
			return ErrUnsavedRelated
		}
		if r.parent.coll == nil || t.coll == nil || !sameSessionIdentity(r.parent.coll.session, t.coll.session) {
			return ErrSessionMismatch
		}
	}

	rows, err := r.parent.coll.session.executor.Query(ctx, "SELECT tag_id FROM post_tags WHERE post_id = $1;", r.parent.current.ID)
	if err != nil {
		return err
	}
	current := make(map[pgtype.UUID]bool)
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			rows.Close()
			return err
		}
		current[id] = true
	}
	if err := rows.Err(); err != nil {
		rows.Close()
		return err
	}
	rows.Close()

	desired := make(map[pgtype.UUID]bool, len(targets))
	for _, t := range targets {
		desired[t.current.ID] = true
	}

	for id := range current {
		if !desired[id] {
			if _, err := r.parent.coll.session.executor.Exec(ctx, "DELETE FROM post_tags WHERE post_id = $1 AND tag_id = $2;", r.parent.current.ID, id); err != nil {
				return err
			}
		}
	}
	for id := range desired {
		if !current[id] {
			if _, err := r.parent.coll.session.executor.Exec(ctx, "INSERT INTO post_tags (post_id, tag_id) VALUES ($1, $2);", r.parent.current.ID, id); err != nil {
				return err
			}
		}
	}
	return nil
}
