// Code generated by sqlc-gen-richmodel. DO NOT EDIT.
package content

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgxpool"
)

type richmodelExecutor interface {
	Exec(context.Context, string, ...any) (pgconn.CommandTag, error)
	Query(context.Context, string, ...any) (pgx.Rows, error)
	QueryRow(context.Context, string, ...any) pgx.Row
}

type sessionIdentity struct{}

// Session owns the database connection pool and one collection per
// configured model in this context.
type Session struct {
	pool        *pgxpool.Pool
	executor    richmodelExecutor
	identity    *sessionIdentity
	lazyLoading LazyLoadingMode
	Users       *UserCollection
	Posts       *PostCollection
	Tags        *TagCollection
}

// SessionOption configures optional Session behavior at construction time.
type SessionOption func(*Session)

// LazyLoadingMode controls whether an uncached lazy relation read is
// allowed, logged, or prevented (FR-020; contracts/relation-api.md).
type LazyLoadingMode uint8

const (
	// LazyLoadingAllowed performs uncached lazy reads normally (default).
	LazyLoadingAllowed LazyLoadingMode = iota
	// LazyLoadingLogged performs uncached lazy reads but reports them via
	// the session's configured Logger, if any.
	LazyLoadingLogged
	// LazyLoadingPrevented rejects an uncached lazy read with
	// ErrLazyLoadingPrevented instead of performing it. Reads of an
	// already-loaded or eager-loaded relation are unaffected.
	LazyLoadingPrevented
)

// WithLazyLoading sets mode as the session's lazy-loading policy.
func WithLazyLoading(mode LazyLoadingMode) SessionOption {
	return func(s *Session) { s.lazyLoading = mode }
}

// New creates a Session backed by pool, with every context model's
// collection attached.
func New(pool *pgxpool.Pool, opts ...SessionOption) *Session {
	s := &Session{pool: pool, executor: pool, identity: &sessionIdentity{}}
	for _, opt := range opts {
		opt(s)
	}
	s.initCollections()
	return s
}

func (s *Session) initCollections() {
	s.Users = newUserCollection(s)
	s.Posts = newPostCollection(s)
	s.Tags = newTagCollection(s)
}

// Transaction runs fn inside one database transaction. fn receives a fresh
// transaction-scoped session; returning nil commits, returning an error
// rolls back and returns that error, and panicking rolls back before the
// panic continues.
func (s *Session) Transaction(ctx context.Context, fn func(*Session) error) error {
	if s.pool == nil {
		return ErrTransactionUnavailable
	}
	tx, err := s.pool.Begin(ctx)
	if err != nil {
		return err
	}

	txSession := &Session{executor: tx, identity: &sessionIdentity{}, lazyLoading: s.lazyLoading}
	txSession.initCollections()

	closed := false
	defer func() {
		if !closed {
			_ = tx.Rollback(ctx)
		}
	}()

	if err := fn(txSession); err != nil {
		_ = tx.Rollback(ctx)
		closed = true
		return err
	}
	if err := tx.Commit(ctx); err != nil {
		closed = true
		return err
	}
	closed = true
	return nil
}

func sameSessionIdentity(a, b *Session) bool {
	return a != nil && b != nil && a.identity == b.identity
}

// modelState is a generated model's lifecycle state (contracts/
// generated-model-api.md's "Lifecycle-state queries").
type modelState uint8

const (
	modelStateNew modelState = iota
	modelStatePersisted
	modelStateDeleted
)

// Sentinel errors returned by every generated model's terminal methods.
var (
	// ErrDeletedModel is returned by Save/Refresh on a deleted model.
	ErrDeletedModel = errors.New("richmodel: model is deleted")
	// ErrDetachedModel is returned by Save/Delete/Refresh on a model with
	// no owning session.
	ErrDetachedModel = errors.New("richmodel: model is not attached to a session")
	// ErrImmutableField is recorded as a field-level error when a setter
	// for an immutable_after_insert field is called on a persisted model.
	ErrImmutableField = errors.New("richmodel: field is immutable after insert")
	// ErrOperationNotConfigured is returned by Save/Delete/Refresh when the
	// underlying lifecycle operation they need has no configured query.
	ErrOperationNotConfigured = errors.New("richmodel: operation has no configured query")
	// ErrTransactionUnavailable is returned when Transaction is called on a
	// session that cannot open a new database transaction.
	ErrTransactionUnavailable = errors.New("richmodel: transaction is unavailable on this session")
	// ErrNotFound is returned by single-record fetches when no row matches.
	ErrNotFound = errors.New("richmodel: not found")
	// ErrSessionMismatch is returned by Associate/Attach/Sync when the
	// related model belongs to a different session than the parent.
	ErrSessionMismatch = errors.New("richmodel: related model belongs to a different session")
	// ErrUnsavedRelated is returned by Associate/Attach/Sync when the
	// related model has no persisted identifier (IsNew()).
	ErrUnsavedRelated = errors.New("richmodel: related model has no persisted identifier")
	// ErrLazyLoadingPrevented is returned by a relation's Get/Reload when
	// the session's LazyLoadingMode is LazyLoadingPrevented and the
	// relation is not already cached or eager-loaded.
	ErrLazyLoadingPrevented = errors.New("richmodel: lazy loading of an uncached relation is prevented")
)

// cloneScopeValues copies src so a relation builder's scope methods can
// chain new values without mutating the receiver or any other builder
// value already in hand (FR-010).
func cloneScopeValues(src map[string]any) map[string]any {
	dst := make(map[string]any, len(src)+1)
	for k, v := range src {
		dst[k] = v
	}
	return dst
}

// relationScopeArg resolves a scope-bound query parameter's value: whatever
// a chained scope set, or def when no scope in the chain set it.
func relationScopeArg(values map[string]any, key string, def any) any {
	if v, ok := values[key]; ok {
		return v
	}
	return def
}
