// Code generated by sqlc-gen-richmodel. DO NOT EDIT.
package content

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
)

// tagStore executes Tag's configured sqlc queries directly via
// pgx, using each query's already-validated, already-parameterized SQL text
// exactly as sqlc's own generated code would (sqlc-gen-go embeds this same
// query.Text verbatim as its query constant) — the query itself remains
// sqlc's statically-verified output; this adapter only executes it.
type tagStore struct {
	executor richmodelExecutor
}

func newTagStore(executor richmodelExecutor) *tagStore {
	return &tagStore{executor: executor}
}

func (s *tagStore) find(ctx context.Context, rec tagRecord) (tagRecord, error) {
	var out tagRecord
	row := s.executor.QueryRow(ctx, "SELECT id, name FROM tags WHERE id = $1;", rec.ID)
	if err := row.Scan(&out.ID, &out.Name); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return tagRecord{}, ErrNotFound
		}
		return tagRecord{}, classifyDatabaseError(err)
	}
	return out, nil
}

func (s *tagStore) insert(ctx context.Context, rec tagRecord) (tagRecord, error) {
	var out tagRecord
	row := s.executor.QueryRow(ctx, "INSERT INTO tags (name) VALUES ($1) RETURNING id, name;", rec.Name)
	if err := row.Scan(&out.ID, &out.Name); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return tagRecord{}, ErrNotFound
		}
		return tagRecord{}, classifyDatabaseError(err)
	}
	return out, nil
}
