// Code generated by sqlc-gen-richmodel. DO NOT EDIT.
package content

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

// UserCollection constructs and finds User instances, attached to
// the session that produced it.
type UserCollection struct {
	session *Session
	store   *userStore
}

func newUserCollection(sess *Session) *UserCollection {
	return &UserCollection{session: sess, store: newUserStore(sess.executor)}
}

// New constructs a new, unpersisted User attached to this collection.
func (c *UserCollection) New() *User {
	return &User{coll: c, state: modelStateNew}
}

// Query starts a statically configured User query chain.
func (c *UserCollection) Query() UserQuery {
	return UserQuery{coll: c}
}

type UserQuery struct {
	coll      *UserCollection
	querySQL  string
	active    bool
	limit     int32
	withPosts bool
}

func (q UserQuery) Active() UserQuery {
	q.active = true
	return q
}

func (q UserQuery) Limit(limit int32) UserQuery {
	q.limit = limit
	return q
}

func (q UserQuery) OrderByName() UserQuery {
	q.querySQL = "SELECT id, name FROM users WHERE active = $1 ORDER BY name LIMIT $2;"
	return q
}

func (q UserQuery) WithPosts() UserQuery {
	q.withPosts = true
	return q
}

func (q UserQuery) Get(ctx context.Context) ([]*User, error) {
	sql := "SELECT id, name FROM users WHERE active = $1 ORDER BY id LIMIT $2;"
	if q.querySQL != "" {
		sql = q.querySQL
	}
	rows, err := q.coll.session.executor.Query(ctx, sql, q.active, q.limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var out []*User
	for rows.Next() {
		var rec userRecord
		if err := rows.Scan(&rec.ID, &rec.Name); err != nil {
			return nil, err
		}
		u := &User{coll: q.coll, state: modelStatePersisted}
		u.current, u.original = rec, rec
		out = append(out, u)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	if q.withPosts {
		if err := q.coll.EagerLoad(ctx, out, WithPosts()); err != nil {
			return nil, err
		}
	}
	return out, nil
}

// Find looks up a persisted User by its configured find operation.
func (c *UserCollection) Find(ctx context.Context, id pgtype.UUID) (*User, error) {
	rec, err := c.store.find(ctx, userRecord{
		ID: id,
	})
	if err != nil {
		return nil, err
	}
	u := &User{coll: c, state: modelStatePersisted}
	u.current, u.original = rec, rec
	return u, nil
}

func (c *UserCollection) FindByName(ctx context.Context, name string) (*User, error) {
	var rec userRecord
	row := c.session.executor.QueryRow(ctx, "SELECT id, name FROM users WHERE name = $1;", name)
	if err := row.Scan(&rec.ID, &rec.Name); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, ErrNotFound
		}
		return nil, err
	}
	u := &User{coll: c, state: modelStatePersisted}
	u.current, u.original = rec, rec
	return u, nil
}
