// Code generated by sqlc-gen-richmodel. DO NOT EDIT.
package content

import (
	"context"
	"log"
)

// UserPostsRelation is a lazy, chainable accessor for User's
// Posts relation. See contracts/relation-api.md for the full
// contract every generated relation builder satisfies. Builder values are
// immutable by convention: chaining a scope returns a new value and never
// mutates r, the parent model, or another builder value (FR-010).
type UserPostsRelation struct {
	parent       *User
	scopeValues  map[string]any
	variantQuery string
}

// Posts returns a new UserPostsRelation for u. Constructing it
// performs no data access (FR-012); call Get to read.
func (u *User) Posts() UserPostsRelation {
	return UserPostsRelation{parent: u}
}

func (r UserPostsRelation) isScoped() bool {
	return len(r.scopeValues) > 0 || r.variantQuery != ""
}

func (r UserPostsRelation) exec(ctx context.Context) ([]*Post, error) {
	sqlText := "SELECT id, user_id, title FROM posts WHERE user_id = $1 AND (published = $2 OR $2 IS NULL);"

	rows, err := r.parent.coll.session.executor.Query(ctx, sqlText, r.parent.current.ID, relationScopeArg(r.scopeValues, "published", nil))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []*Post
	for rows.Next() {
		var rec postRecord
		if err := rows.Scan(&rec.ID, &rec.UserID, &rec.Title); err != nil {
			return nil, err
		}
		t := &Post{coll: r.parent.coll.session.Posts, state: modelStatePersisted}
		t.current, t.original = rec, rec
		t.authorCache = r.parent
		t.authorLoaded = true
		out = append(out, t)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return out, nil
}

// Get executes Posts's lazy query on cache miss for an unscoped
// call, or returns the cached value if already loaded (FR-012, FR-016). A
// scoped call always performs its own data access and never touches the
// canonical cache (FR-019).
func (r UserPostsRelation) Get(ctx context.Context) ([]*Post, error) {
	if !r.isScoped() {
		if r.parent.postsLoaded {
			return r.parent.postsCache, nil
		}
		switch r.parent.coll.session.lazyLoading {
		case LazyLoadingPrevented:
			return nil, ErrLazyLoadingPrevented
		case LazyLoadingLogged:
			log.Printf("richmodel: uncached lazy load of User.Posts")
		}
	}
	result, err := r.exec(ctx)
	if err != nil {
		return nil, err
	}
	if !r.isScoped() {
		r.parent.postsCache = result
		r.parent.postsLoaded = true
	}
	return result, nil
}

// Reload clears Posts's canonical cache and performs a fresh
// read unconditionally.
func (r UserPostsRelation) Reload(ctx context.Context) ([]*Post, error) {
	result, err := r.exec(ctx)
	if err != nil {
		return nil, err
	}
	if !r.isScoped() {
		r.parent.postsCache = result
		r.parent.postsLoaded = true
	}
	return result, nil
}

// Cached returns Posts's canonical cached value without
// performing any data access (FR-016).
func (r UserPostsRelation) Cached() ([]*Post, bool) {
	return r.parent.postsCache, r.parent.postsLoaded
}

// Loaded reports whether Posts's canonical value is already
// loaded, without performing any data access (FR-016).
func (r UserPostsRelation) Loaded() bool {
	return r.parent.postsLoaded
}

// Forget clears Posts's canonical cache without performing any
// data access (FR-018).
func (r UserPostsRelation) Forget() *User {
	r.parent.postsCache = nil
	r.parent.postsLoaded = false
	return r.parent
}

// New constructs a new, session-attached, not-yet-persisted Post, with Posts's foreign key pre-assigned. It does not persist the child.
func (r UserPostsRelation) New() *Post {
	t := &Post{coll: r.parent.coll.session.Posts, state: modelStateNew}
	t.current.UserID = r.parent.current.ID
	return t
}

// Published chains a fixed-value scope onto UserPostsRelation (FR-009);
// does not mutate r or the parent model (FR-010).
func (r UserPostsRelation) Published() UserPostsRelation {
	r2 := r
	r2.scopeValues = cloneScopeValues(r.scopeValues)
	r2.scopeValues["published"] = true
	return r2
}
