// Code generated by sqlc-gen-richmodel. DO NOT EDIT.
package content

import (
	"context"
	"errors"
	"fmt"
	"strings"

	"github.com/jackc/pgx/v5/pgtype"
)

// User is a generated Active-Record-style model. See
// contracts/generated-model-api.md for the full contract every generated
// model satisfies.
type User struct {
	current  userRecord
	original userRecord
	errs     map[UserField]error
	state    modelState
	coll     *UserCollection
}

// ID returns User's current ID value.
func (u *User) ID() pgtype.UUID { return u.current.ID }

// Name returns User's current Name value.
func (u *User) Name() string { return u.current.Name }

// Email returns User's current Email value.
func (u *User) Email() string { return u.current.Email }

// Active returns User's current Active value.
func (u *User) Active() bool { return u.current.Active }

// CreatedAt returns User's current CreatedAt value.
func (u *User) CreatedAt() pgtype.Timestamptz { return u.current.CreatedAt }

// UpdatedAt returns User's current UpdatedAt value.
func (u *User) UpdatedAt() pgtype.Timestamptz { return u.current.UpdatedAt }

// SetName sets User's Name and updates its dirty state.
func (u *User) SetName(value string) *User {
	u.current.Name = value
	u.clearFieldError(UserFieldName)
	return u
}

// SetEmail sets User's Email and updates its dirty state.
func (u *User) SetEmail(value string) *User {
	u.current.Email = value
	u.clearFieldError(UserFieldEmail)
	return u
}

// SetActive sets User's Active and updates its dirty state.
func (u *User) SetActive(value bool) *User {
	u.current.Active = value
	u.clearFieldError(UserFieldActive)
	return u
}

// OriginalID returns User's last-persisted ID value.
func (u *User) OriginalID() pgtype.UUID { return u.original.ID }

// OriginalName returns User's last-persisted Name value.
func (u *User) OriginalName() string { return u.original.Name }

// OriginalEmail returns User's last-persisted Email value.
func (u *User) OriginalEmail() string { return u.original.Email }

// OriginalActive returns User's last-persisted Active value.
func (u *User) OriginalActive() bool { return u.original.Active }

// OriginalCreatedAt returns User's last-persisted CreatedAt value.
func (u *User) OriginalCreatedAt() pgtype.Timestamptz { return u.original.CreatedAt }

// OriginalUpdatedAt returns User's last-persisted UpdatedAt value.
func (u *User) OriginalUpdatedAt() pgtype.Timestamptz { return u.original.UpdatedAt }

func (u *User) fieldEqual(f UserField) bool {
	switch f {
	case UserFieldID:
		return u.current.ID == u.original.ID
	case UserFieldName:
		return u.current.Name == u.original.Name
	case UserFieldEmail:
		return u.current.Email == u.original.Email
	case UserFieldActive:
		return u.current.Active == u.original.Active
	case UserFieldCreatedAt:
		return u.current.CreatedAt == u.original.CreatedAt
	case UserFieldUpdatedAt:
		return u.current.UpdatedAt == u.original.UpdatedAt
	}
	return true
}

// IsDirty reports whether any of fields differ from their original,
// last-persisted values; with no arguments, the whole model is considered.
func (u *User) IsDirty(fields ...UserField) bool {
	if len(fields) == 0 {
		for f := UserField(0); f < UserFieldCount; f++ {
			if !u.fieldEqual(f) {
				return true
			}
		}
		return false
	}
	for _, f := range fields {
		if !u.fieldEqual(f) {
			return true
		}
	}
	return false
}

// IsClean is the inverse of IsDirty.
func (u *User) IsClean(fields ...UserField) bool { return !u.IsDirty(fields...) }

// DirtyFields returns every dirty field, in declared field order.
func (u *User) DirtyFields() []UserField {
	var out []UserField
	for f := UserField(0); f < UserFieldCount; f++ {
		if !u.fieldEqual(f) {
			out = append(out, f)
		}
	}
	return out
}

// Err aggregates every current field error via errors.Join; nil if there
// are none.
func (u *User) Err() error {
	if len(u.errs) == 0 {
		return nil
	}
	var errs []error
	for f := UserField(0); f < UserFieldCount; f++ {
		if err, ok := u.errs[f]; ok {
			errs = append(errs, err)
		}
	}
	return errors.Join(errs...)
}

// HasErrors reports whether User has any current field error.
func (u *User) HasErrors() bool { return len(u.errs) > 0 }

// FieldError returns f's current error, or nil.
func (u *User) FieldError(f UserField) error { return u.errs[f] }

// ClearErrors discards every current field error.
func (u *User) ClearErrors() *User {
	u.errs = nil
	return u
}

// setFieldError is the sanctioned way handwritten extension code sets a
// field error without bypassing public setter behavior (FR-019). Setting a
// new error for a field replaces any previous error for that field.
func (u *User) setFieldError(f UserField, err error) *User {
	if u.errs == nil {
		u.errs = make(map[UserField]error)
	}
	u.errs[f] = err
	return u
}

// clearFieldError is the sanctioned way handwritten extension code clears a
// field error without bypassing public setter behavior (FR-019).
func (u *User) clearFieldError(f UserField) *User {
	delete(u.errs, f)
	return u
}

// Exists reports whether User has ever been persisted.
func (u *User) Exists() bool { return u.state != modelStateNew }

// IsNew reports whether User has never been persisted.
func (u *User) IsNew() bool { return u.state == modelStateNew }

// IsDeleted reports whether User has been deleted.
func (u *User) IsDeleted() bool { return u.state == modelStateDeleted }

// IsAttached reports whether User is attached to an owning session.
func (u *User) IsAttached() bool { return u.coll != nil }

// Save validates first; inserts if new, does nothing if persisted and
// clean, updates if persisted and dirty. Returns ErrDeletedModel or
// ErrDetachedModel if User is deleted or not attached.
func (u *User) Save(ctx context.Context) error {
	if u.state == modelStateDeleted {
		return ErrDeletedModel
	}
	if !u.IsAttached() {
		return ErrDetachedModel
	}
	if u.HasErrors() {
		return u.Err()
	}
	switch {
	case u.state == modelStateNew:
		out, err := u.coll.store.insert(ctx, u.current)
		if err != nil {
			return err
		}
		u.current, u.original = out, out
		u.state = modelStatePersisted
		return nil
	case u.IsClean():
		return nil
	default:
		out, err := u.coll.store.update(ctx, u.current)
		if err != nil {
			return err
		}
		u.current, u.original = out, out
		return nil
	}
}

// Delete deletes User; idempotent if already deleted. Returns
// ErrDetachedModel if User is not attached.
func (u *User) Delete(ctx context.Context) error {
	if u.state == modelStateDeleted {
		return nil
	}
	if !u.IsAttached() {
		return ErrDetachedModel
	}
	if _, err := u.coll.store.delete(ctx, u.current); err != nil {
		return err
	}
	u.state = modelStateDeleted
	return nil
}

// Refresh re-hydrates User from the database and re-synchronizes its
// original snapshot. Returns ErrDeletedModel or ErrDetachedModel if
// User is deleted or not attached.
func (u *User) Refresh(ctx context.Context) error {
	if u.state == modelStateDeleted {
		return ErrDeletedModel
	}
	if !u.IsAttached() {
		return ErrDetachedModel
	}
	out, err := u.coll.store.refresh(ctx, u.current)
	if err != nil {
		return err
	}
	u.current, u.original = out, out
	return nil
}

// String renders User for diagnostics, omitting the value of every
// field marked sensitive (FR-014).
func (u *User) String() string {
	fields := []string{
		fmt.Sprintf("ID=%v", u.current.ID),
		fmt.Sprintf("Name=%v", u.current.Name),
		fmt.Sprintf("Email=%v", u.current.Email),
		fmt.Sprintf("Active=%v", u.current.Active),
		fmt.Sprintf("CreatedAt=%v", u.current.CreatedAt),
		fmt.Sprintf("UpdatedAt=%v", u.current.UpdatedAt),
	}
	return fmt.Sprintf("User{%s}", strings.Join(fields, ", "))
}
