// Code generated by sqlc-gen-richmodel. DO NOT EDIT.
package content

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
)

// userStore executes User's configured sqlc queries directly via
// pgx, using each query's already-validated, already-parameterized SQL text
// exactly as sqlc's own generated code would (sqlc-gen-go embeds this same
// query.Text verbatim as its query constant) — the query itself remains
// sqlc's statically-verified output; this adapter only executes it.
type userStore struct {
	executor richmodelExecutor
}

func newUserStore(executor richmodelExecutor) *userStore {
	return &userStore{executor: executor}
}

func (s *userStore) find(ctx context.Context, rec userRecord) (userRecord, error) {
	var out userRecord
	row := s.executor.QueryRow(ctx, "SELECT id, name, email, active, created_at, updated_at FROM users WHERE id = $1;", rec.ID)
	if err := row.Scan(&out.ID, &out.Name, &out.Email, &out.Active, &out.CreatedAt, &out.UpdatedAt); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return userRecord{}, ErrNotFound
		}
		return userRecord{}, classifyDatabaseError(err)
	}
	return out, nil
}

func (s *userStore) insert(ctx context.Context, rec userRecord) (userRecord, error) {
	var out userRecord
	row := s.executor.QueryRow(ctx, "INSERT INTO users (name, email, active) VALUES ($1, $2, $3) RETURNING id, name, email, active, created_at, updated_at;", rec.Name, rec.Email, rec.Active)
	if err := row.Scan(&out.ID, &out.Name, &out.Email, &out.Active, &out.CreatedAt, &out.UpdatedAt); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return userRecord{}, ErrNotFound
		}
		return userRecord{}, classifyDatabaseError(err)
	}
	return out, nil
}

func (s *userStore) update(ctx context.Context, rec userRecord) (userRecord, error) {
	var out userRecord
	row := s.executor.QueryRow(ctx, "UPDATE users SET name = $1, email = $2, active = $3, updated_at = NOW() WHERE id = $4 RETURNING id, name, email, active, created_at, updated_at;", rec.Name, rec.Email, rec.Active, rec.ID)
	if err := row.Scan(&out.ID, &out.Name, &out.Email, &out.Active, &out.CreatedAt, &out.UpdatedAt); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return userRecord{}, ErrNotFound
		}
		return userRecord{}, classifyDatabaseError(err)
	}
	return out, nil
}

func (s *userStore) delete(ctx context.Context, rec userRecord) (int64, error) {
	tag, err := s.executor.Exec(ctx, "DELETE FROM users WHERE id = $1;", rec.ID)
	if err != nil {
		return 0, classifyDatabaseError(err)
	}
	return tag.RowsAffected(), nil
}

func (s *userStore) refresh(ctx context.Context, rec userRecord) (userRecord, error) {
	var out userRecord
	row := s.executor.QueryRow(ctx, "SELECT id, name, email, active, created_at, updated_at FROM users WHERE id = $1;", rec.ID)
	if err := row.Scan(&out.ID, &out.Name, &out.Email, &out.Active, &out.CreatedAt, &out.UpdatedAt); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return userRecord{}, ErrNotFound
		}
		return userRecord{}, classifyDatabaseError(err)
	}
	return out, nil
}
