blank_issues_enabled: true
contact_links:
  - name: Question or discussion
    url: https://github.com/macoaure/sqlc-gen-richmodel/discussions
    about: Ask a question or start a discussion about using sqlc-gen-richmodel.
