// Code generated by sqlc-gen-richmodel. DO NOT EDIT.
package content

import (
	"context"
	"errors"
	"log"

	"github.com/jackc/pgx/v5"
)

// PostAuthorRelation is a lazy, chainable accessor for Post's
// Author relation. See contracts/relation-api.md for the full
// contract every generated relation builder satisfies. Builder values are
// immutable by convention: chaining a scope returns a new value and never
// mutates r, the parent model, or another builder value (FR-010).
type PostAuthorRelation struct {
	parent       *Post
	scopeValues  map[string]any
	variantQuery string
}

// Author returns a new PostAuthorRelation for u. Constructing it
// performs no data access (FR-012); call Get to read.
func (u *Post) Author() PostAuthorRelation {
	return PostAuthorRelation{parent: u}
}

func (r PostAuthorRelation) isScoped() bool {
	return len(r.scopeValues) > 0 || r.variantQuery != ""
}

func (r PostAuthorRelation) exec(ctx context.Context) (*User, error) {
	sqlText := "SELECT id, name FROM users WHERE id = $1;"

	row := r.parent.coll.session.executor.QueryRow(ctx, sqlText, r.parent.current.UserID)
	var rec userRecord
	if err := row.Scan(&rec.ID, &rec.Name); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, nil
		}
		return nil, err
	}
	t := &User{coll: r.parent.coll.session.Users, state: modelStatePersisted}
	t.current, t.original = rec, rec
	t.postsCache = append(t.postsCache, r.parent)
	t.postsLoaded = true
	return t, nil
}

// Get executes Author's lazy query on cache miss for an unscoped
// call, or returns the cached value if already loaded (FR-012, FR-016). A
// scoped call always performs its own data access and never touches the
// canonical cache (FR-019).
func (r PostAuthorRelation) Get(ctx context.Context) (*User, error) {
	if !r.isScoped() {
		if r.parent.authorLoaded {
			return r.parent.authorCache, nil
		}
		switch r.parent.coll.session.lazyLoading {
		case LazyLoadingPrevented:
			return nil, ErrLazyLoadingPrevented
		case LazyLoadingLogged:
			log.Printf("richmodel: uncached lazy load of Post.Author")
		}
	}
	result, err := r.exec(ctx)
	if err != nil {
		return nil, err
	}
	if !r.isScoped() {
		r.parent.authorCache = result
		r.parent.authorLoaded = true
	}
	return result, nil
}

// Reload clears Author's canonical cache and performs a fresh
// read unconditionally.
func (r PostAuthorRelation) Reload(ctx context.Context) (*User, error) {
	result, err := r.exec(ctx)
	if err != nil {
		return nil, err
	}
	if !r.isScoped() {
		r.parent.authorCache = result
		r.parent.authorLoaded = true
	}
	return result, nil
}

// Cached returns Author's canonical cached value without
// performing any data access (FR-016).
func (r PostAuthorRelation) Cached() (*User, bool) {
	return r.parent.authorCache, r.parent.authorLoaded
}

// Loaded reports whether Author's canonical value is already
// loaded, without performing any data access (FR-016).
func (r PostAuthorRelation) Loaded() bool {
	return r.parent.authorLoaded
}

// Forget clears Author's canonical cache without performing any
// data access (FR-018).
func (r PostAuthorRelation) Forget() *Post {
	r.parent.authorCache = nil
	r.parent.authorLoaded = false
	return r.parent
}

// Associate assigns target as Post's Author, in
// memory only (call Save to persist). Rejects target if it belongs to a
// different session or has no persisted identifier (FR-021).
func (r PostAuthorRelation) Associate(target *User) error {
	if target.IsNew() {
		return ErrUnsavedRelated
	}
	if r.parent.coll == nil || target.coll == nil || !sameSessionIdentity(r.parent.coll.session, target.coll.session) {
		return ErrSessionMismatch
	}
	r.parent.current.UserID = target.current.ID
	r.parent.authorCache = target
	r.parent.authorLoaded = true
	return nil
}
