// Code generated by sqlc-gen-richmodel. DO NOT EDIT.
package content

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

// PostCollection constructs and finds Post instances, attached to
// the session that produced it.
type PostCollection struct {
	session *Session
	store   *postStore
}

func newPostCollection(sess *Session) *PostCollection {
	return &PostCollection{session: sess, store: newPostStore(sess.executor)}
}

// New constructs a new, unpersisted Post attached to this collection.
func (c *PostCollection) New() *Post {
	return &Post{coll: c, state: modelStateNew}
}

// Find looks up a persisted Post by its configured find operation.
func (c *PostCollection) Find(ctx context.Context, id pgtype.UUID) (*Post, error) {
	rec, err := c.store.find(ctx, postRecord{
		ID: id,
	})
	if err != nil {
		return nil, err
	}
	u := &Post{coll: c, state: modelStatePersisted}
	u.current, u.original = rec, rec
	return u, nil
}
