// Code generated by sqlc-gen-richmodel. DO NOT EDIT.
package content

import (
	"context"

	"github.com/jackc/pgx/v5/pgxpool"
)

// tagStore executes Tag's configured sqlc queries directly via
// pgx, using each query's already-validated, already-parameterized SQL text
// exactly as sqlc's own generated code would (sqlc-gen-go embeds this same
// query.Text verbatim as its query constant) — the query itself remains
// sqlc's statically-verified output; this adapter only executes it.
type tagStore struct {
	pool *pgxpool.Pool
}

func newTagStore(pool *pgxpool.Pool) *tagStore {
	return &tagStore{pool: pool}
}

func (s *tagStore) find(ctx context.Context, rec tagRecord) (tagRecord, error) {
	var out tagRecord
	row := s.pool.QueryRow(ctx, "SELECT id, name FROM tags WHERE id = $1;", rec.ID)
	if err := row.Scan(&out.ID, &out.Name); err != nil {
		return tagRecord{}, err
	}
	return out, nil
}

func (s *tagStore) insert(ctx context.Context, rec tagRecord) (tagRecord, error) {
	var out tagRecord
	row := s.pool.QueryRow(ctx, "INSERT INTO tags (name) VALUES ($1) RETURNING id, name;", rec.Name)
	if err := row.Scan(&out.ID, &out.Name); err != nil {
		return tagRecord{}, err
	}
	return out, nil
}
