// Code generated by sqlc-gen-richmodel. DO NOT EDIT.
package content

import (
	"context"
	"errors"
	"fmt"
	"strings"

	"github.com/jackc/pgx/v5/pgtype"
)

// Tag is a generated Active-Record-style model. See
// contracts/generated-model-api.md for the full contract every generated
// model satisfies.
type Tag struct {
	current  tagRecord
	original tagRecord
	errs     map[TagField]error
	state    modelState
	coll     *TagCollection
}

// ID returns Tag's current ID value.
func (u *Tag) ID() pgtype.UUID { return u.current.ID }

// Name returns Tag's current Name value.
func (u *Tag) Name() string { return u.current.Name }

// SetName sets Tag's Name and updates its dirty state.
func (u *Tag) SetName(value string) *Tag {
	u.current.Name = value
	u.clearFieldError(TagFieldName)
	return u
}

// OriginalID returns Tag's last-persisted ID value.
func (u *Tag) OriginalID() pgtype.UUID { return u.original.ID }

// OriginalName returns Tag's last-persisted Name value.
func (u *Tag) OriginalName() string { return u.original.Name }

func (u *Tag) fieldEqual(f TagField) bool {
	switch f {
	case TagFieldID:
		return u.current.ID == u.original.ID
	case TagFieldName:
		return u.current.Name == u.original.Name
	}
	return true
}

// IsDirty reports whether any of fields differ from their original,
// last-persisted values; with no arguments, the whole model is considered.
func (u *Tag) IsDirty(fields ...TagField) bool {
	if len(fields) == 0 {
		for f := TagField(0); f < TagFieldCount; f++ {
			if !u.fieldEqual(f) {
				return true
			}
		}
		return false
	}
	for _, f := range fields {
		if !u.fieldEqual(f) {
			return true
		}
	}
	return false
}

// IsClean is the inverse of IsDirty.
func (u *Tag) IsClean(fields ...TagField) bool { return !u.IsDirty(fields...) }

// DirtyFields returns every dirty field, in declared field order.
func (u *Tag) DirtyFields() []TagField {
	var out []TagField
	for f := TagField(0); f < TagFieldCount; f++ {
		if !u.fieldEqual(f) {
			out = append(out, f)
		}
	}
	return out
}

// Err aggregates every current field error via errors.Join; nil if there
// are none.
func (u *Tag) Err() error {
	if len(u.errs) == 0 {
		return nil
	}
	var errs []error
	for f := TagField(0); f < TagFieldCount; f++ {
		if err, ok := u.errs[f]; ok {
			errs = append(errs, err)
		}
	}
	return errors.Join(errs...)
}

// HasErrors reports whether Tag has any current field error.
func (u *Tag) HasErrors() bool { return len(u.errs) > 0 }

// FieldError returns f's current error, or nil.
func (u *Tag) FieldError(f TagField) error { return u.errs[f] }

// ClearErrors discards every current field error.
func (u *Tag) ClearErrors() *Tag {
	u.errs = nil
	return u
}

// setFieldError is the sanctioned way handwritten extension code sets a
// field error without bypassing public setter behavior (FR-019). Setting a
// new error for a field replaces any previous error for that field.
func (u *Tag) setFieldError(f TagField, err error) *Tag {
	if u.errs == nil {
		u.errs = make(map[TagField]error)
	}
	u.errs[f] = err
	return u
}

// clearFieldError is the sanctioned way handwritten extension code clears a
// field error without bypassing public setter behavior (FR-019).
func (u *Tag) clearFieldError(f TagField) *Tag {
	delete(u.errs, f)
	return u
}

// Exists reports whether Tag has ever been persisted.
func (u *Tag) Exists() bool { return u.state != modelStateNew }

// IsNew reports whether Tag has never been persisted.
func (u *Tag) IsNew() bool { return u.state == modelStateNew }

// IsDeleted reports whether Tag has been deleted.
func (u *Tag) IsDeleted() bool { return u.state == modelStateDeleted }

// IsAttached reports whether Tag is attached to an owning session.
func (u *Tag) IsAttached() bool { return u.coll != nil }

// Save validates first; inserts if new, does nothing if persisted and
// clean, updates if persisted and dirty. Returns ErrDeletedModel or
// ErrDetachedModel if Tag is deleted or not attached.
func (u *Tag) Save(ctx context.Context) error {
	if u.state == modelStateDeleted {
		return ErrDeletedModel
	}
	if !u.IsAttached() {
		return ErrDetachedModel
	}
	if u.HasErrors() {
		return u.Err()
	}
	switch {
	case u.state == modelStateNew:
		out, err := u.coll.store.insert(ctx, u.current)
		if err != nil {
			return err
		}
		u.current, u.original = out, out
		u.state = modelStatePersisted
		return nil
	case u.IsClean():
		return nil
	default:
		return ErrOperationNotConfigured
	}
}

// Delete deletes Tag; idempotent if already deleted. Returns
// ErrDetachedModel if Tag is not attached.
func (u *Tag) Delete(ctx context.Context) error {
	if u.state == modelStateDeleted {
		return nil
	}
	if !u.IsAttached() {
		return ErrDetachedModel
	}
	return ErrOperationNotConfigured
}

// Refresh re-hydrates Tag from the database and re-synchronizes its
// original snapshot. Returns ErrDeletedModel or ErrDetachedModel if
// Tag is deleted or not attached.
func (u *Tag) Refresh(ctx context.Context) error {
	if u.state == modelStateDeleted {
		return ErrDeletedModel
	}
	if !u.IsAttached() {
		return ErrDetachedModel
	}
	return ErrOperationNotConfigured
}

// String renders Tag for diagnostics, omitting the value of every
// field marked sensitive (FR-014).
func (u *Tag) String() string {
	fields := []string{
		fmt.Sprintf("ID=%v", u.current.ID),
		fmt.Sprintf("Name=%v", u.current.Name),
	}
	return fmt.Sprintf("Tag{%s}", strings.Join(fields, ", "))
}
