// Code generated by sqlc-gen-richmodel. DO NOT EDIT.
package content

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/jackc/pgx/v5/pgxpool"
)

// TagCollection constructs and finds Tag instances, attached to
// the session that produced it.
type TagCollection struct {
	session *Session
	store   *tagStore
}

func newTagCollection(sess *Session, pool *pgxpool.Pool) *TagCollection {
	return &TagCollection{session: sess, store: newTagStore(pool)}
}

// New constructs a new, unpersisted Tag attached to this collection.
func (c *TagCollection) New() *Tag {
	return &Tag{coll: c, state: modelStateNew}
}

// Find looks up a persisted Tag by its configured find operation.
func (c *TagCollection) Find(ctx context.Context, id pgtype.UUID) (*Tag, error) {
	rec, err := c.store.find(ctx, tagRecord{
		ID: id,
	})
	if err != nil {
		return nil, err
	}
	u := &Tag{coll: c, state: modelStatePersisted}
	u.current, u.original = rec, rec
	return u, nil
}
