// Code generated by sqlc-gen-richmodel. DO NOT EDIT.
package content

import (
	"context"

	"github.com/jackc/pgx/v5/pgxpool"
)

// userStore executes User's configured sqlc queries directly via
// pgx, using each query's already-validated, already-parameterized SQL text
// exactly as sqlc's own generated code would (sqlc-gen-go embeds this same
// query.Text verbatim as its query constant) — the query itself remains
// sqlc's statically-verified output; this adapter only executes it.
type userStore struct {
	pool *pgxpool.Pool
}

func newUserStore(pool *pgxpool.Pool) *userStore {
	return &userStore{pool: pool}
}

func (s *userStore) find(ctx context.Context, rec userRecord) (userRecord, error) {
	var out userRecord
	row := s.pool.QueryRow(ctx, "SELECT id, name FROM users WHERE id = $1;", rec.ID)
	if err := row.Scan(&out.ID, &out.Name); err != nil {
		return userRecord{}, err
	}
	return out, nil
}

func (s *userStore) insert(ctx context.Context, rec userRecord) (userRecord, error) {
	var out userRecord
	row := s.pool.QueryRow(ctx, "INSERT INTO users (name) VALUES ($1) RETURNING id, name;", rec.Name)
	if err := row.Scan(&out.ID, &out.Name); err != nil {
		return userRecord{}, err
	}
	return out, nil
}
