// Code generated by sqlc-gen-richmodel. DO NOT EDIT.
package content

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// postRecord is Post's generated current/original value shape, one
// field per column returned by its canonical (insert) query, in that query's
// column order.
type postRecord struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
	Title  string
}
