// Code generated by sqlc-model. DO NOT EDIT.
package content

import (
	"context"
	"errors"
	"fmt"
	"strings"

	"github.com/jackc/pgx/v5/pgtype"
)

// Post is a generated Active-Record-style model. See
// contracts/generated-model-api.md for the full contract every generated
// model satisfies.
type Post struct {
	current      postRecord
	original     postRecord
	errs         map[PostField]error
	state        modelState
	coll         *PostCollection
	authorCache  *User
	authorLoaded bool
	tagsCache    []*Tag
	tagsLoaded   bool
}

// ID returns Post's current ID value.
func (u *Post) ID() pgtype.UUID { return u.current.ID }

// UserID returns Post's current UserID value.
func (u *Post) UserID() pgtype.UUID { return u.current.UserID }

// Title returns Post's current Title value.
func (u *Post) Title() string { return u.current.Title }

// SetUserID sets Post's UserID and updates its dirty state.
func (u *Post) SetUserID(value pgtype.UUID) *Post {
	u.current.UserID = value
	u.clearFieldError(PostFieldUserID)
	return u
}

// SetTitle sets Post's Title and updates its dirty state.
func (u *Post) SetTitle(value string) *Post {
	u.current.Title = value
	u.clearFieldError(PostFieldTitle)
	return u
}

// OriginalID returns Post's last-persisted ID value.
func (u *Post) OriginalID() pgtype.UUID { return u.original.ID }

// OriginalUserID returns Post's last-persisted UserID value.
func (u *Post) OriginalUserID() pgtype.UUID { return u.original.UserID }

// OriginalTitle returns Post's last-persisted Title value.
func (u *Post) OriginalTitle() string { return u.original.Title }

func (u *Post) fieldEqual(f PostField) bool {
	switch f {
	case PostFieldID:
		return u.current.ID == u.original.ID
	case PostFieldUserID:
		return u.current.UserID == u.original.UserID
	case PostFieldTitle:
		return u.current.Title == u.original.Title
	}
	return true
}

// IsDirty reports whether any of fields differ from their original,
// last-persisted values; with no arguments, the whole model is considered.
func (u *Post) IsDirty(fields ...PostField) bool {
	if len(fields) == 0 {
		for f := PostField(0); f < PostFieldCount; f++ {
			if !u.fieldEqual(f) {
				return true
			}
		}
		return false
	}
	for _, f := range fields {
		if !u.fieldEqual(f) {
			return true
		}
	}
	return false
}

// IsClean is the inverse of IsDirty.
func (u *Post) IsClean(fields ...PostField) bool { return !u.IsDirty(fields...) }

// HasChanges reports whether any current field differs from its baseline.
func (u *Post) HasChanges() bool {
	if u.state == modelStateDeleted {
		return false
	}
	return u.IsDirty()
}

// DirtyFields returns every dirty field, in declared field order.
func (u *Post) DirtyFields() []PostField {
	var out []PostField
	for f := PostField(0); f < PostFieldCount; f++ {
		if !u.fieldEqual(f) {
			out = append(out, f)
		}
	}
	return out
}

func (u *Post) fieldErr() error {
	if len(u.errs) == 0 {
		return nil
	}
	var errs []error
	for f := PostField(0); f < PostFieldCount; f++ {
		if err, ok := u.errs[f]; ok {
			errs = append(errs, u.validationError(f, err))
		}
	}
	return errors.Join(errs...)
}

func (u *Post) validationError(f PostField, err error) error {
	switch f {
	case PostFieldID:
		return ValidationError{Model: "Post", Field: "id", Err: err}
	case PostFieldUserID:
		return ValidationError{Model: "Post", Field: "user_id", Err: err}
	case PostFieldTitle:
		return ValidationError{Model: "Post", Field: "title", Err: err}
	default:
		return ValidationError{Model: "Post", Field: fmt.Sprint(f), Err: err}
	}
}

// Err aggregates every current validation error; nil if there are none.
func (u *Post) Err() error { return u.Validate() }

// Validate combines current field errors with any handwritten cross-field
// validation hook declared in Post's extension file.
func (u *Post) Validate() error {
	var custom error
	if v, ok := any(u).(interface{ validatePost() error }); ok {
		custom = v.validatePost()
	}
	return errors.Join(u.fieldErr(), custom)
}

// HasErrors reports whether Post has any current validation error.
func (u *Post) HasErrors() bool { return u.Validate() != nil }

// FieldError returns f's current error, or nil.
func (u *Post) FieldError(f PostField) error { return u.errs[f] }

// ClearErrors discards every current field error.
func (u *Post) ClearErrors() *Post {
	u.errs = nil
	return u
}

// setFieldError is the sanctioned way handwritten extension code sets a
// field error without bypassing public setter behavior (FR-019). Setting a
// new error for a field replaces any previous error for that field.
func (u *Post) setFieldError(f PostField, err error) *Post {
	if u.errs == nil {
		u.errs = make(map[PostField]error)
	}
	u.errs[f] = err
	return u
}

// clearFieldError is the sanctioned way handwritten extension code clears a
// field error without bypassing public setter behavior (FR-019).
func (u *Post) clearFieldError(f PostField) *Post {
	delete(u.errs, f)
	return u
}

// Exists reports whether Post has ever been persisted.
func (u *Post) Exists() bool { return u.state != modelStateNew }

// IsPersisted reports whether Post currently has a persisted backing row.
func (u *Post) IsPersisted() bool { return u.state == modelStatePersisted }

// IsNew reports whether Post has never been persisted.
func (u *Post) IsNew() bool { return u.state == modelStateNew }

// IsDeleted reports whether Post has been deleted.
func (u *Post) IsDeleted() bool { return u.state == modelStateDeleted }

// IsAttached reports whether Post is attached to an owning session.
func (u *Post) IsAttached() bool { return u.coll != nil }

// IsDetached reports whether Post has no owning session.
func (u *Post) IsDetached() bool { return !u.IsAttached() }

// Detach returns a copy of Post without an owning session.
func (u *Post) Detach() *Post {
	v := *u
	v.coll = nil
	return &v
}

// Save validates first; inserts if new, does nothing if persisted and
// clean, updates if persisted and dirty. Returns ErrModelDeleted or
// ErrModelDetached if Post is deleted or not attached.
func (u *Post) Save(ctx context.Context) error {
	if u.state == modelStateDeleted {
		return ErrModelDeleted
	}
	if !u.IsAttached() {
		return ErrModelDetached
	}
	if err := u.Validate(); err != nil {
		return err
	}
	switch {
	case u.state == modelStateNew:
		out, err := u.coll.store.insert(ctx, u.current)
		if err != nil {
			return err
		}
		u.current, u.original = out, out
		u.state = modelStatePersisted
		return nil
	case u.IsClean():
		return nil
	default:
		return ErrOperationNotConfigured
	}
}

// Delete deletes Post; idempotent if already deleted. Returns
// ErrModelDetached if Post is not attached.
func (u *Post) Delete(ctx context.Context) error {
	if u.state == modelStateDeleted {
		return nil
	}
	if !u.IsAttached() {
		return ErrModelDetached
	}
	if u.state == modelStateNew {
		return ErrModelNotPersisted
	}
	return ErrOperationNotConfigured
}

// Refresh re-hydrates Post from the database and re-synchronizes its
// original snapshot. Returns ErrModelDeleted or ErrModelDetached if
// Post is deleted or not attached.
func (u *Post) Refresh(ctx context.Context) error {
	if u.state == modelStateDeleted {
		return ErrModelDeleted
	}
	if !u.IsAttached() {
		return ErrModelDetached
	}
	if u.state == modelStateNew {
		return ErrModelNotPersisted
	}
	return ErrOperationNotConfigured
}

// String renders Post for diagnostics, omitting the value of every
// field marked sensitive (FR-014).
func (u *Post) String() string {
	fields := []string{
		fmt.Sprintf("ID=%v", u.current.ID),
		fmt.Sprintf("UserID=%v", u.current.UserID),
		fmt.Sprintf("Title=%v", u.current.Title),
	}
	return fmt.Sprintf("Post{%s}", strings.Join(fields, ", "))
}
