// Code generated by sqlc-gen-richmodel. DO NOT EDIT.
package content

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

// userEagerLoadPlan accumulates which of User's eager-loadable relations a
// caller has requested via With<Relation> option constructors.
type userEagerLoadPlan struct {
	loadPosts   bool
	nestedPosts []func(UserPostsEagerLoad) UserPostsEagerLoad
}

// UserEagerLoadOption configures one relation to eager-load for a batch of
// User instances (contracts/relation-api.md).
type UserEagerLoadOption func(*userEagerLoadPlan)

// UserPostsEagerLoad composes nested eager loads for User.Posts's own
// eager-loadable relations (FR-014) — With<Relation> methods exist only for
// relations on Post that themselves have an eager_query configured.
type UserPostsEagerLoad struct {
}

// WithPosts is a UserEagerLoadOption constructor requesting
// User.Posts be eager-loaded (FR-013). Generated only because
// Posts has an eager_query configured.
func WithPosts(nested ...func(UserPostsEagerLoad) UserPostsEagerLoad) UserEagerLoadOption {
	return func(p *userEagerLoadPlan) {
		p.loadPosts = true
		p.nestedPosts = append(append([]func(UserPostsEagerLoad) UserPostsEagerLoad{}, p.nestedPosts...), nested...)
	}
}

// EagerLoad populates the requested relations' canonical caches for every
// element of parents in one batch data-access operation per relation level
// (FR-013, SC-002), including nested relations requested via
// With<Relation>(func(o) { return o.With<Nested>() }) (FR-014), and
// populates each related record's configured inverse cache with the
// already-known parent instance (FR-015).
func (c *UserCollection) EagerLoad(ctx context.Context, parents []*User, opts ...UserEagerLoadOption) error {
	if len(parents) == 0 {
		return nil
	}
	var p userEagerLoadPlan
	for _, opt := range opts {
		opt(&p)
	}

	if p.loadPosts {
		if err := c.eagerLoadPosts(ctx, parents, p.nestedPosts); err != nil {
			return err
		}
	}

	return nil
}

func (c *UserCollection) eagerLoadPosts(ctx context.Context, parents []*User, nested []func(UserPostsEagerLoad) UserPostsEagerLoad) error {
	keys := make([]pgtype.UUID, 0, len(parents))
	byKey := make(map[pgtype.UUID][]*User, len(parents))
	for _, parent := range parents {
		key := parent.current.ID
		keys = append(keys, key)
		byKey[key] = append(byKey[key], parent)
	}

	rows, err := c.session.executor.Query(ctx, "SELECT id, user_id, title FROM posts WHERE user_id = ANY($1);", keys)
	if err != nil {
		return err
	}
	defer rows.Close()

	grouped := make(map[pgtype.UUID][]*Post)
	var allTargets []*Post
	for rows.Next() {
		var rec postRecord
		if err := rows.Scan(&rec.ID, &rec.UserID, &rec.Title); err != nil {
			return err
		}
		t := &Post{coll: c.session.Posts, state: modelStatePersisted}
		t.current, t.original = rec, rec
		fk := rec.UserID
		grouped[fk] = append(grouped[fk], t)
		allTargets = append(allTargets, t)
	}
	if err := rows.Err(); err != nil {
		return err
	}

	for key, ps := range byKey {
		related := grouped[key]
		for _, parent := range ps {
			parent.postsCache = related
			parent.postsLoaded = true
			for _, t := range related {
				t.authorCache = parent
				t.authorLoaded = true
			}
		}
	}

	return nil
}
