// Code generated by sqlc-gen-richmodel. DO NOT EDIT.
package inventory

// WidgetField identifies one field of Widget, in declared field order.
type WidgetField uint8

const (
	WidgetFieldID WidgetField = iota
	WidgetFieldVersionNo
	WidgetFieldReadonlyField
	WidgetFieldFillableField
	WidgetFieldMutableField
	WidgetFieldFillableAndMutable
	WidgetFieldGeneratedInsertField
	WidgetFieldGeneratedSaveField
	WidgetFieldSensitiveField
	WidgetFieldExplicitMapped
	WidgetFieldImmutableField
	WidgetFieldCount
)
