// Code generated by sqlc-gen-richmodel. DO NOT EDIT.
package inventory

import (
	"errors"

	"github.com/jackc/pgx/v5/pgxpool"
)

// Session owns the database connection pool and one collection per
// configured model in this context.
type Session struct {
	pool    *pgxpool.Pool
	Widgets *WidgetCollection
}

// New creates a Session backed by pool, with every context model's
// collection attached.
func New(pool *pgxpool.Pool) *Session {
	s := &Session{pool: pool}
	s.Widgets = newWidgetCollection(s, pool)
	return s
}

// modelState is a generated model's lifecycle state (contracts/
// generated-model-api.md's "Lifecycle-state queries").
type modelState uint8

const (
	modelStateNew modelState = iota
	modelStatePersisted
	modelStateDeleted
)

// Sentinel errors returned by every generated model's terminal methods.
var (
	// ErrDeletedModel is returned by Save/Refresh on a deleted model.
	ErrDeletedModel = errors.New("richmodel: model is deleted")
	// ErrDetachedModel is returned by Save/Delete/Refresh on a model with
	// no owning session.
	ErrDetachedModel = errors.New("richmodel: model is not attached to a session")
	// ErrImmutableField is recorded as a field-level error when a setter
	// for an immutable_after_insert field is called on a persisted model.
	ErrImmutableField = errors.New("richmodel: field is immutable after insert")
	// ErrOperationNotConfigured is returned by Save/Delete/Refresh when the
	// underlying lifecycle operation they need has no configured query.
	ErrOperationNotConfigured = errors.New("richmodel: operation has no configured query")
)
