// Code generated by sqlc-model. DO NOT EDIT.
package inventory

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
)

// widgetStore executes Widget's configured sqlc queries directly via
// pgx, using each query's already-validated, already-parameterized SQL text
// exactly as sqlc's own generated code would (sqlc-gen-go embeds this same
// query.Text verbatim as its query constant) — the query itself remains
// sqlc's statically-verified output; this adapter only executes it.
type widgetStore struct {
	executor richmodelExecutor
}

func newWidgetStore(executor richmodelExecutor) *widgetStore {
	return &widgetStore{executor: executor}
}

func (s *widgetStore) find(ctx context.Context, rec widgetRecord) (widgetRecord, error) {
	var out widgetRecord
	row := s.executor.QueryRow(ctx, "SELECT id, version_no, readonly_field, fillable_field, mutable_field, fillable_and_mutable, generated_insert_field, generated_save_field, sensitive_field, actual_column_name, immutable_field FROM widgets WHERE id = $1;", rec.ID)
	if err := row.Scan(&out.ID, &out.VersionNo, &out.ReadonlyField, &out.FillableField, &out.MutableField, &out.FillableAndMutable, &out.GeneratedInsertField, &out.GeneratedSaveField, &out.SensitiveField, &out.ExplicitMapped, &out.ImmutableField); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return widgetRecord{}, ErrNotFound
		}
		return widgetRecord{}, classifyDatabaseError(err)
	}
	return out, nil
}

func (s *widgetStore) insert(ctx context.Context, rec widgetRecord) (widgetRecord, error) {
	var out widgetRecord
	row := s.executor.QueryRow(ctx, "INSERT INTO widgets (fillable_field, mutable_field, fillable_and_mutable, actual_column_name, immutable_field) VALUES ($1, $2, $3, $4, $5) RETURNING id, version_no, readonly_field, fillable_field, mutable_field, fillable_and_mutable, generated_insert_field, generated_save_field, sensitive_field, actual_column_name, immutable_field;", rec.FillableField, rec.MutableField, rec.FillableAndMutable, rec.ExplicitMapped, rec.ImmutableField)
	if err := row.Scan(&out.ID, &out.VersionNo, &out.ReadonlyField, &out.FillableField, &out.MutableField, &out.FillableAndMutable, &out.GeneratedInsertField, &out.GeneratedSaveField, &out.SensitiveField, &out.ExplicitMapped, &out.ImmutableField); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return widgetRecord{}, ErrNotFound
		}
		return widgetRecord{}, classifyDatabaseError(err)
	}
	return out, nil
}

func (s *widgetStore) update(ctx context.Context, rec widgetRecord) (widgetRecord, error) {
	var out widgetRecord
	row := s.executor.QueryRow(ctx, "UPDATE widgets SET fillable_field = $1, mutable_field = $2, fillable_and_mutable = $3, actual_column_name = $4, immutable_field = $5 WHERE id = $6 RETURNING id, version_no, readonly_field, fillable_field, mutable_field, fillable_and_mutable, generated_insert_field, generated_save_field, sensitive_field, actual_column_name, immutable_field;", rec.FillableField, rec.MutableField, rec.FillableAndMutable, rec.ExplicitMapped, rec.ImmutableField, rec.ID)
	if err := row.Scan(&out.ID, &out.VersionNo, &out.ReadonlyField, &out.FillableField, &out.MutableField, &out.FillableAndMutable, &out.GeneratedInsertField, &out.GeneratedSaveField, &out.SensitiveField, &out.ExplicitMapped, &out.ImmutableField); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return widgetRecord{}, ErrNotFound
		}
		return widgetRecord{}, classifyDatabaseError(err)
	}
	return out, nil
}

func (s *widgetStore) delete(ctx context.Context, rec widgetRecord) (int64, error) {
	tag, err := s.executor.Exec(ctx, "DELETE FROM widgets WHERE id = $1;", rec.ID)
	if err != nil {
		return 0, classifyDatabaseError(err)
	}
	return tag.RowsAffected(), nil
}

func (s *widgetStore) refresh(ctx context.Context, rec widgetRecord) (widgetRecord, error) {
	var out widgetRecord
	row := s.executor.QueryRow(ctx, "SELECT id, version_no, readonly_field, fillable_field, mutable_field, fillable_and_mutable, generated_insert_field, generated_save_field, sensitive_field, actual_column_name, immutable_field FROM widgets WHERE id = $1;", rec.ID)
	if err := row.Scan(&out.ID, &out.VersionNo, &out.ReadonlyField, &out.FillableField, &out.MutableField, &out.FillableAndMutable, &out.GeneratedInsertField, &out.GeneratedSaveField, &out.SensitiveField, &out.ExplicitMapped, &out.ImmutableField); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return widgetRecord{}, ErrNotFound
		}
		return widgetRecord{}, classifyDatabaseError(err)
	}
	return out, nil
}
