// Code generated by sqlc-gen-richmodel. DO NOT EDIT.
package inventory

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/jackc/pgx/v5/pgxpool"
)

// WidgetCollection constructs and finds Widget instances, attached to
// the session that produced it.
type WidgetCollection struct {
	session *Session
	store   *widgetStore
}

func newWidgetCollection(sess *Session, pool *pgxpool.Pool) *WidgetCollection {
	return &WidgetCollection{session: sess, store: newWidgetStore(pool)}
}

// New constructs a new, unpersisted Widget attached to this collection.
func (c *WidgetCollection) New() *Widget {
	return &Widget{coll: c, state: modelStateNew}
}

// Find looks up a persisted Widget by its configured find operation.
func (c *WidgetCollection) Find(ctx context.Context, id pgtype.UUID) (*Widget, error) {
	rec, err := c.store.find(ctx, widgetRecord{
		ID: id,
	})
	if err != nil {
		return nil, err
	}
	u := &Widget{coll: c, state: modelStatePersisted}
	u.current, u.original = rec, rec
	return u, nil
}
