// Code generated by sqlc-gen-richmodel. DO NOT EDIT.
package inventory

import (
	"context"
	"errors"
	"fmt"
	"strings"

	"github.com/jackc/pgx/v5/pgtype"
)

// Widget is a generated Active-Record-style model. See
// contracts/generated-model-api.md for the full contract every generated
// model satisfies.
type Widget struct {
	current  widgetRecord
	original widgetRecord
	errs     map[WidgetField]error
	state    modelState
	coll     *WidgetCollection
}

// ID returns Widget's current ID value.
func (u *Widget) ID() pgtype.UUID { return u.current.ID }

// VersionNo returns Widget's current VersionNo value.
func (u *Widget) VersionNo() int32 { return u.current.VersionNo }

// ReadonlyField returns Widget's current ReadonlyField value.
func (u *Widget) ReadonlyField() string { return u.current.ReadonlyField }

// FillableField returns Widget's current FillableField value.
func (u *Widget) FillableField() string { return u.current.FillableField }

// MutableField returns Widget's current MutableField value.
func (u *Widget) MutableField() string { return u.current.MutableField }

// FillableAndMutable returns Widget's current FillableAndMutable value.
func (u *Widget) FillableAndMutable() string { return u.current.FillableAndMutable }

// GeneratedInsertField returns Widget's current GeneratedInsertField value.
func (u *Widget) GeneratedInsertField() string { return u.current.GeneratedInsertField }

// GeneratedSaveField returns Widget's current GeneratedSaveField value.
func (u *Widget) GeneratedSaveField() string { return u.current.GeneratedSaveField }

// SensitiveField returns Widget's current SensitiveField value.
func (u *Widget) SensitiveField() string { return u.current.SensitiveField }

// ExplicitMapped returns Widget's current ExplicitMapped value.
func (u *Widget) ExplicitMapped() string { return u.current.ExplicitMapped }

// ImmutableField returns Widget's current ImmutableField value.
func (u *Widget) ImmutableField() string { return u.current.ImmutableField }

// SetFillableField sets Widget's FillableField and updates its dirty state.
func (u *Widget) SetFillableField(value string) *Widget {
	u.current.FillableField = value
	u.clearFieldError(WidgetFieldFillableField)
	return u
}

// SetMutableField sets Widget's MutableField and updates its dirty state.
func (u *Widget) SetMutableField(value string) *Widget {
	u.current.MutableField = value
	u.clearFieldError(WidgetFieldMutableField)
	return u
}

// SetFillableAndMutable sets Widget's FillableAndMutable and updates its dirty state.
func (u *Widget) SetFillableAndMutable(value string) *Widget {
	u.current.FillableAndMutable = value
	u.clearFieldError(WidgetFieldFillableAndMutable)
	return u
}

// SetExplicitMapped sets Widget's ExplicitMapped and updates its dirty state.
func (u *Widget) SetExplicitMapped(value string) *Widget {
	u.current.ExplicitMapped = value
	u.clearFieldError(WidgetFieldExplicitMapped)
	return u
}

// SetImmutableField sets Widget's ImmutableField and updates its dirty state.
func (u *Widget) SetImmutableField(value string) *Widget {
	if !u.IsNew() {
		u.setFieldError(WidgetFieldImmutableField, ErrImmutableField)
		return u
	}
	u.current.ImmutableField = value
	u.clearFieldError(WidgetFieldImmutableField)
	return u
}

// OriginalID returns Widget's last-persisted ID value.
func (u *Widget) OriginalID() pgtype.UUID { return u.original.ID }

// OriginalVersionNo returns Widget's last-persisted VersionNo value.
func (u *Widget) OriginalVersionNo() int32 { return u.original.VersionNo }

// OriginalReadonlyField returns Widget's last-persisted ReadonlyField value.
func (u *Widget) OriginalReadonlyField() string { return u.original.ReadonlyField }

// OriginalFillableField returns Widget's last-persisted FillableField value.
func (u *Widget) OriginalFillableField() string { return u.original.FillableField }

// OriginalMutableField returns Widget's last-persisted MutableField value.
func (u *Widget) OriginalMutableField() string { return u.original.MutableField }

// OriginalFillableAndMutable returns Widget's last-persisted FillableAndMutable value.
func (u *Widget) OriginalFillableAndMutable() string { return u.original.FillableAndMutable }

// OriginalGeneratedInsertField returns Widget's last-persisted GeneratedInsertField value.
func (u *Widget) OriginalGeneratedInsertField() string { return u.original.GeneratedInsertField }

// OriginalGeneratedSaveField returns Widget's last-persisted GeneratedSaveField value.
func (u *Widget) OriginalGeneratedSaveField() string { return u.original.GeneratedSaveField }

// OriginalSensitiveField returns Widget's last-persisted SensitiveField value.
func (u *Widget) OriginalSensitiveField() string { return u.original.SensitiveField }

// OriginalExplicitMapped returns Widget's last-persisted ExplicitMapped value.
func (u *Widget) OriginalExplicitMapped() string { return u.original.ExplicitMapped }

// OriginalImmutableField returns Widget's last-persisted ImmutableField value.
func (u *Widget) OriginalImmutableField() string { return u.original.ImmutableField }

func (u *Widget) fieldEqual(f WidgetField) bool {
	switch f {
	case WidgetFieldID:
		return u.current.ID == u.original.ID
	case WidgetFieldVersionNo:
		return u.current.VersionNo == u.original.VersionNo
	case WidgetFieldReadonlyField:
		return u.current.ReadonlyField == u.original.ReadonlyField
	case WidgetFieldFillableField:
		return u.current.FillableField == u.original.FillableField
	case WidgetFieldMutableField:
		return u.current.MutableField == u.original.MutableField
	case WidgetFieldFillableAndMutable:
		return u.current.FillableAndMutable == u.original.FillableAndMutable
	case WidgetFieldGeneratedInsertField:
		return u.current.GeneratedInsertField == u.original.GeneratedInsertField
	case WidgetFieldGeneratedSaveField:
		return u.current.GeneratedSaveField == u.original.GeneratedSaveField
	case WidgetFieldSensitiveField:
		return u.current.SensitiveField == u.original.SensitiveField
	case WidgetFieldExplicitMapped:
		return u.current.ExplicitMapped == u.original.ExplicitMapped
	case WidgetFieldImmutableField:
		return u.current.ImmutableField == u.original.ImmutableField
	}
	return true
}

// IsDirty reports whether any of fields differ from their original,
// last-persisted values; with no arguments, the whole model is considered.
func (u *Widget) IsDirty(fields ...WidgetField) bool {
	if len(fields) == 0 {
		for f := WidgetField(0); f < WidgetFieldCount; f++ {
			if !u.fieldEqual(f) {
				return true
			}
		}
		return false
	}
	for _, f := range fields {
		if !u.fieldEqual(f) {
			return true
		}
	}
	return false
}

// IsClean is the inverse of IsDirty.
func (u *Widget) IsClean(fields ...WidgetField) bool { return !u.IsDirty(fields...) }

// HasChanges reports whether any current field differs from its baseline.
func (u *Widget) HasChanges() bool {
	if u.state == modelStateDeleted {
		return false
	}
	return u.IsDirty()
}

// DirtyFields returns every dirty field, in declared field order.
func (u *Widget) DirtyFields() []WidgetField {
	var out []WidgetField
	for f := WidgetField(0); f < WidgetFieldCount; f++ {
		if !u.fieldEqual(f) {
			out = append(out, f)
		}
	}
	return out
}

func (u *Widget) fieldErr() error {
	if len(u.errs) == 0 {
		return nil
	}
	var errs []error
	for f := WidgetField(0); f < WidgetFieldCount; f++ {
		if err, ok := u.errs[f]; ok {
			errs = append(errs, u.validationError(f, err))
		}
	}
	return errors.Join(errs...)
}

func (u *Widget) validationError(f WidgetField, err error) error {
	switch f {
	case WidgetFieldID:
		return ValidationError{Model: "Widget", Field: "id", Err: err}
	case WidgetFieldVersionNo:
		return ValidationError{Model: "Widget", Field: "version_no", Err: err}
	case WidgetFieldReadonlyField:
		return ValidationError{Model: "Widget", Field: "readonly_field", Err: err}
	case WidgetFieldFillableField:
		return ValidationError{Model: "Widget", Field: "fillable_field", Err: err}
	case WidgetFieldMutableField:
		return ValidationError{Model: "Widget", Field: "mutable_field", Err: err}
	case WidgetFieldFillableAndMutable:
		return ValidationError{Model: "Widget", Field: "fillable_and_mutable", Err: err}
	case WidgetFieldGeneratedInsertField:
		return ValidationError{Model: "Widget", Field: "generated_insert_field", Err: err}
	case WidgetFieldGeneratedSaveField:
		return ValidationError{Model: "Widget", Field: "generated_save_field", Err: err}
	case WidgetFieldSensitiveField:
		return ValidationError{Model: "Widget", Field: "sensitive_field", Err: err}
	case WidgetFieldExplicitMapped:
		return ValidationError{Model: "Widget", Field: "explicit_mapped", Err: err}
	case WidgetFieldImmutableField:
		return ValidationError{Model: "Widget", Field: "immutable_field", Err: err}
	default:
		return ValidationError{Model: "Widget", Field: fmt.Sprint(f), Err: err}
	}
}

// Err aggregates every current validation error; nil if there are none.
func (u *Widget) Err() error { return u.Validate() }

// Validate combines current field errors with any handwritten cross-field
// validation hook declared in Widget's extension file.
func (u *Widget) Validate() error {
	var custom error
	if v, ok := any(u).(interface{ validateWidget() error }); ok {
		custom = v.validateWidget()
	}
	return errors.Join(u.fieldErr(), custom)
}

// HasErrors reports whether Widget has any current validation error.
func (u *Widget) HasErrors() bool { return u.Validate() != nil }

// FieldError returns f's current error, or nil.
func (u *Widget) FieldError(f WidgetField) error { return u.errs[f] }

// ClearErrors discards every current field error.
func (u *Widget) ClearErrors() *Widget {
	u.errs = nil
	return u
}

// setFieldError is the sanctioned way handwritten extension code sets a
// field error without bypassing public setter behavior (FR-019). Setting a
// new error for a field replaces any previous error for that field.
func (u *Widget) setFieldError(f WidgetField, err error) *Widget {
	if u.errs == nil {
		u.errs = make(map[WidgetField]error)
	}
	u.errs[f] = err
	return u
}

// clearFieldError is the sanctioned way handwritten extension code clears a
// field error without bypassing public setter behavior (FR-019).
func (u *Widget) clearFieldError(f WidgetField) *Widget {
	delete(u.errs, f)
	return u
}

// Exists reports whether Widget has ever been persisted.
func (u *Widget) Exists() bool { return u.state != modelStateNew }

// IsPersisted reports whether Widget currently has a persisted backing row.
func (u *Widget) IsPersisted() bool { return u.state == modelStatePersisted }

// IsNew reports whether Widget has never been persisted.
func (u *Widget) IsNew() bool { return u.state == modelStateNew }

// IsDeleted reports whether Widget has been deleted.
func (u *Widget) IsDeleted() bool { return u.state == modelStateDeleted }

// IsAttached reports whether Widget is attached to an owning session.
func (u *Widget) IsAttached() bool { return u.coll != nil }

// IsDetached reports whether Widget has no owning session.
func (u *Widget) IsDetached() bool { return !u.IsAttached() }

// Detach returns a copy of Widget without an owning session.
func (u *Widget) Detach() *Widget {
	v := *u
	v.coll = nil
	return &v
}

// Save validates first; inserts if new, does nothing if persisted and
// clean, updates if persisted and dirty. Returns ErrModelDeleted or
// ErrModelDetached if Widget is deleted or not attached.
func (u *Widget) Save(ctx context.Context) error {
	if u.state == modelStateDeleted {
		return ErrModelDeleted
	}
	if !u.IsAttached() {
		return ErrModelDetached
	}
	if err := u.Validate(); err != nil {
		return err
	}
	switch {
	case u.state == modelStateNew:
		out, err := u.coll.store.insert(ctx, u.current)
		if err != nil {
			return err
		}
		u.current, u.original = out, out
		u.state = modelStatePersisted
		return nil
	case u.IsClean():
		return nil
	default:
		out, err := u.coll.store.update(ctx, u.current)
		if err != nil {
			return err
		}
		u.current, u.original = out, out
		return nil
	}
}

// Delete deletes Widget; idempotent if already deleted. Returns
// ErrModelDetached if Widget is not attached.
func (u *Widget) Delete(ctx context.Context) error {
	if u.state == modelStateDeleted {
		return nil
	}
	if !u.IsAttached() {
		return ErrModelDetached
	}
	if u.state == modelStateNew {
		return ErrModelNotPersisted
	}
	if _, err := u.coll.store.delete(ctx, u.current); err != nil {
		return err
	}
	u.original = u.current
	u.state = modelStateDeleted
	return nil
}

// Refresh re-hydrates Widget from the database and re-synchronizes its
// original snapshot. Returns ErrModelDeleted or ErrModelDetached if
// Widget is deleted or not attached.
func (u *Widget) Refresh(ctx context.Context) error {
	if u.state == modelStateDeleted {
		return ErrModelDeleted
	}
	if !u.IsAttached() {
		return ErrModelDetached
	}
	if u.state == modelStateNew {
		return ErrModelNotPersisted
	}
	out, err := u.coll.store.refresh(ctx, u.current)
	if err != nil {
		return err
	}
	u.current, u.original = out, out
	return nil
}

// String renders Widget for diagnostics, omitting the value of every
// field marked sensitive (FR-014).
func (u *Widget) String() string {
	fields := []string{
		fmt.Sprintf("ID=%v", u.current.ID),
		fmt.Sprintf("VersionNo=%v", u.current.VersionNo),
		fmt.Sprintf("ReadonlyField=%v", u.current.ReadonlyField),
		fmt.Sprintf("FillableField=%v", u.current.FillableField),
		fmt.Sprintf("MutableField=%v", u.current.MutableField),
		fmt.Sprintf("FillableAndMutable=%v", u.current.FillableAndMutable),
		fmt.Sprintf("GeneratedInsertField=%v", u.current.GeneratedInsertField),
		fmt.Sprintf("GeneratedSaveField=%v", u.current.GeneratedSaveField),
		"SensitiveField=<redacted>",
		fmt.Sprintf("ExplicitMapped=%v", u.current.ExplicitMapped),
		fmt.Sprintf("ImmutableField=%v", u.current.ImmutableField),
	}
	return fmt.Sprintf("Widget{%s}", strings.Join(fields, ", "))
}
