// Code generated by sqlc-gen-richmodel. DO NOT EDIT.
package inventory

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// widgetRecord is the raw persisted shape of Widget, one field per
// column returned by its canonical (insert) query, in that query's column
// order.
type widgetRecord struct {
	ID                   pgtype.UUID
	VersionNo            int32
	ReadonlyField        string
	FillableField        string
	MutableField         string
	FillableAndMutable   string
	GeneratedInsertField string
	GeneratedSaveField   string
	SensitiveField       string
	ExplicitMapped       string
	ImmutableField       string
}
