// Code generated by sqlc-gen-richmodel. DO NOT EDIT.
package content

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
)

// postStore executes Post's configured sqlc queries directly via
// pgx, using each query's already-validated, already-parameterized SQL text
// exactly as sqlc's own generated code would (sqlc-gen-go embeds this same
// query.Text verbatim as its query constant) — the query itself remains
// sqlc's statically-verified output; this adapter only executes it.
type postStore struct {
	executor richmodelExecutor
}

func newPostStore(executor richmodelExecutor) *postStore {
	return &postStore{executor: executor}
}

func (s *postStore) find(ctx context.Context, rec postRecord) (postRecord, error) {
	var out postRecord
	row := s.executor.QueryRow(ctx, "SELECT id, user_id, title FROM posts WHERE id = $1;", rec.ID)
	if err := row.Scan(&out.ID, &out.UserID, &out.Title); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return postRecord{}, ErrNotFound
		}
		return postRecord{}, err
	}
	return out, nil
}

func (s *postStore) insert(ctx context.Context, rec postRecord) (postRecord, error) {
	var out postRecord
	row := s.executor.QueryRow(ctx, "INSERT INTO posts (user_id, title) VALUES ($1, $2) RETURNING id, user_id, title;", rec.UserID, rec.Title)
	if err := row.Scan(&out.ID, &out.UserID, &out.Title); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return postRecord{}, ErrNotFound
		}
		return postRecord{}, err
	}
	return out, nil
}
