// Code generated by sqlc-gen-richmodel. DO NOT EDIT.
package content

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// postRecord is the raw persisted shape of Post, one field per
// column returned by its canonical (insert) query, in that query's column
// order.
type postRecord struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
	Title  string
}
