// Code generated by sqlc-model. DO NOT EDIT.
package content

import (
	"context"
	"errors"
	"fmt"
	"strings"

	"github.com/jackc/pgx/v5/pgtype"
)

// Tag is a generated Active-Record-style model. See
// contracts/generated-model-api.md for the full contract every generated
// model satisfies.
type Tag struct {
	current  tagRecord
	original tagRecord
	errs     map[TagField]error
	state    modelState
	coll     *TagCollection
}

// ID returns Tag's current ID value.
func (u *Tag) ID() pgtype.UUID { return u.current.ID }

// Name returns Tag's current Name value.
func (u *Tag) Name() string { return u.current.Name }

// SetName sets Tag's Name and updates its dirty state.
func (u *Tag) SetName(value string) *Tag {
	u.current.Name = value
	u.clearFieldError(TagFieldName)
	return u
}

// OriginalID returns Tag's last-persisted ID value.
func (u *Tag) OriginalID() pgtype.UUID { return u.original.ID }

// OriginalName returns Tag's last-persisted Name value.
func (u *Tag) OriginalName() string { return u.original.Name }

func (u *Tag) fieldEqual(f TagField) bool {
	switch f {
	case TagFieldID:
		return u.current.ID == u.original.ID
	case TagFieldName:
		return u.current.Name == u.original.Name
	}
	return true
}

// IsDirty reports whether any of fields differ from their original,
// last-persisted values; with no arguments, the whole model is considered.
func (u *Tag) IsDirty(fields ...TagField) bool {
	if len(fields) == 0 {
		for f := TagField(0); f < TagFieldCount; f++ {
			if !u.fieldEqual(f) {
				return true
			}
		}
		return false
	}
	for _, f := range fields {
		if !u.fieldEqual(f) {
			return true
		}
	}
	return false
}

// IsClean is the inverse of IsDirty.
func (u *Tag) IsClean(fields ...TagField) bool { return !u.IsDirty(fields...) }

// HasChanges reports whether any current field differs from its baseline.
func (u *Tag) HasChanges() bool {
	if u.state == modelStateDeleted {
		return false
	}
	return u.IsDirty()
}

// DirtyFields returns every dirty field, in declared field order.
func (u *Tag) DirtyFields() []TagField {
	var out []TagField
	for f := TagField(0); f < TagFieldCount; f++ {
		if !u.fieldEqual(f) {
			out = append(out, f)
		}
	}
	return out
}

func (u *Tag) fieldErr() error {
	if len(u.errs) == 0 {
		return nil
	}
	var errs []error
	for f := TagField(0); f < TagFieldCount; f++ {
		if err, ok := u.errs[f]; ok {
			errs = append(errs, u.validationError(f, err))
		}
	}
	return errors.Join(errs...)
}

func (u *Tag) validationError(f TagField, err error) error {
	switch f {
	case TagFieldID:
		return ValidationError{Model: "Tag", Field: "id", Err: err}
	case TagFieldName:
		return ValidationError{Model: "Tag", Field: "name", Err: err}
	default:
		return ValidationError{Model: "Tag", Field: fmt.Sprint(f), Err: err}
	}
}

// Err aggregates every current validation error; nil if there are none.
func (u *Tag) Err() error { return u.Validate() }

// Validate combines current field errors with any handwritten cross-field
// validation hook declared in Tag's extension file.
func (u *Tag) Validate() error {
	var custom error
	if v, ok := any(u).(interface{ validateTag() error }); ok {
		custom = v.validateTag()
	}
	return errors.Join(u.fieldErr(), custom)
}

// HasErrors reports whether Tag has any current validation error.
func (u *Tag) HasErrors() bool { return u.Validate() != nil }

// FieldError returns f's current error, or nil.
func (u *Tag) FieldError(f TagField) error { return u.errs[f] }

// ClearErrors discards every current field error.
func (u *Tag) ClearErrors() *Tag {
	u.errs = nil
	return u
}

// setFieldError is the sanctioned way handwritten extension code sets a
// field error without bypassing public setter behavior (FR-019). Setting a
// new error for a field replaces any previous error for that field.
func (u *Tag) setFieldError(f TagField, err error) *Tag {
	if u.errs == nil {
		u.errs = make(map[TagField]error)
	}
	u.errs[f] = err
	return u
}

// clearFieldError is the sanctioned way handwritten extension code clears a
// field error without bypassing public setter behavior (FR-019).
func (u *Tag) clearFieldError(f TagField) *Tag {
	delete(u.errs, f)
	return u
}

// Exists reports whether Tag has ever been persisted.
func (u *Tag) Exists() bool { return u.state != modelStateNew }

// IsPersisted reports whether Tag currently has a persisted backing row.
func (u *Tag) IsPersisted() bool { return u.state == modelStatePersisted }

// IsNew reports whether Tag has never been persisted.
func (u *Tag) IsNew() bool { return u.state == modelStateNew }

// IsDeleted reports whether Tag has been deleted.
func (u *Tag) IsDeleted() bool { return u.state == modelStateDeleted }

// IsAttached reports whether Tag is attached to an owning session.
func (u *Tag) IsAttached() bool { return u.coll != nil }

// IsDetached reports whether Tag has no owning session.
func (u *Tag) IsDetached() bool { return !u.IsAttached() }

// Detach returns a copy of Tag without an owning session.
func (u *Tag) Detach() *Tag {
	v := *u
	v.coll = nil
	return &v
}

// Save validates first; inserts if new, does nothing if persisted and
// clean, updates if persisted and dirty. Returns ErrModelDeleted or
// ErrModelDetached if Tag is deleted or not attached.
func (u *Tag) Save(ctx context.Context) error {
	if u.state == modelStateDeleted {
		return ErrModelDeleted
	}
	if !u.IsAttached() {
		return ErrModelDetached
	}
	if err := u.Validate(); err != nil {
		return err
	}
	switch {
	case u.state == modelStateNew:
		out, err := u.coll.store.insert(ctx, u.current)
		if err != nil {
			return err
		}
		u.current, u.original = out, out
		u.state = modelStatePersisted
		return nil
	case u.IsClean():
		return nil
	default:
		return ErrOperationNotConfigured
	}
}

// Delete deletes Tag; idempotent if already deleted. Returns
// ErrModelDetached if Tag is not attached.
func (u *Tag) Delete(ctx context.Context) error {
	if u.state == modelStateDeleted {
		return nil
	}
	if !u.IsAttached() {
		return ErrModelDetached
	}
	if u.state == modelStateNew {
		return ErrModelNotPersisted
	}
	return ErrOperationNotConfigured
}

// Refresh re-hydrates Tag from the database and re-synchronizes its
// original snapshot. Returns ErrModelDeleted or ErrModelDetached if
// Tag is deleted or not attached.
func (u *Tag) Refresh(ctx context.Context) error {
	if u.state == modelStateDeleted {
		return ErrModelDeleted
	}
	if !u.IsAttached() {
		return ErrModelDetached
	}
	if u.state == modelStateNew {
		return ErrModelNotPersisted
	}
	return ErrOperationNotConfigured
}

// String renders Tag for diagnostics, omitting the value of every
// field marked sensitive (FR-014).
func (u *Tag) String() string {
	fields := []string{
		fmt.Sprintf("ID=%v", u.current.ID),
		fmt.Sprintf("Name=%v", u.current.Name),
	}
	return fmt.Sprintf("Tag{%s}", strings.Join(fields, ", "))
}
