// Code generated by sqlc-gen-richmodel. DO NOT EDIT.
package content

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// userRecord is the raw persisted shape of User, one field per
// column returned by its canonical (insert) query, in that query's column
// order.
type userRecord struct {
	ID   pgtype.UUID
	Name string
}
