// Code generated by sqlc-gen-richmodel. DO NOT EDIT.
package content

import (
	"context"
	"errors"
	"fmt"
	"strings"

	"github.com/jackc/pgx/v5/pgtype"
)

// User is a generated Active-Record-style model. See
// contracts/generated-model-api.md for the full contract every generated
// model satisfies.
type User struct {
	current     userRecord
	original    userRecord
	errs        map[UserField]error
	state       modelState
	coll        *UserCollection
	postsCache  []*Post
	postsLoaded bool
}

// ID returns User's current ID value.
func (u *User) ID() pgtype.UUID { return u.current.ID }

// Name returns User's current Name value.
func (u *User) Name() string { return u.current.Name }

// SetName sets User's Name and updates its dirty state.
func (u *User) SetName(value string) *User {
	u.current.Name = value
	u.clearFieldError(UserFieldName)
	return u
}

// OriginalID returns User's last-persisted ID value.
func (u *User) OriginalID() pgtype.UUID { return u.original.ID }

// OriginalName returns User's last-persisted Name value.
func (u *User) OriginalName() string { return u.original.Name }

func (u *User) fieldEqual(f UserField) bool {
	switch f {
	case UserFieldID:
		return u.current.ID == u.original.ID
	case UserFieldName:
		return u.current.Name == u.original.Name
	}
	return true
}

// IsDirty reports whether any of fields differ from their original,
// last-persisted values; with no arguments, the whole model is considered.
func (u *User) IsDirty(fields ...UserField) bool {
	if len(fields) == 0 {
		for f := UserField(0); f < UserFieldCount; f++ {
			if !u.fieldEqual(f) {
				return true
			}
		}
		return false
	}
	for _, f := range fields {
		if !u.fieldEqual(f) {
			return true
		}
	}
	return false
}

// IsClean is the inverse of IsDirty.
func (u *User) IsClean(fields ...UserField) bool { return !u.IsDirty(fields...) }

// HasChanges reports whether any current field differs from its baseline.
func (u *User) HasChanges() bool {
	if u.state == modelStateDeleted {
		return false
	}
	return u.IsDirty()
}

// DirtyFields returns every dirty field, in declared field order.
func (u *User) DirtyFields() []UserField {
	var out []UserField
	for f := UserField(0); f < UserFieldCount; f++ {
		if !u.fieldEqual(f) {
			out = append(out, f)
		}
	}
	return out
}

func (u *User) fieldErr() error {
	if len(u.errs) == 0 {
		return nil
	}
	var errs []error
	for f := UserField(0); f < UserFieldCount; f++ {
		if err, ok := u.errs[f]; ok {
			errs = append(errs, err)
		}
	}
	return errors.Join(errs...)
}

// Err aggregates every current validation error; nil if there are none.
func (u *User) Err() error { return u.Validate() }

// Validate combines current field errors with any handwritten cross-field
// validation hook declared in User's extension file.
func (u *User) Validate() error {
	var custom error
	if v, ok := any(u).(interface{ validateUser() error }); ok {
		custom = v.validateUser()
	}
	return errors.Join(u.fieldErr(), custom)
}

// HasErrors reports whether User has any current validation error.
func (u *User) HasErrors() bool { return u.Validate() != nil }

// FieldError returns f's current error, or nil.
func (u *User) FieldError(f UserField) error { return u.errs[f] }

// ClearErrors discards every current field error.
func (u *User) ClearErrors() *User {
	u.errs = nil
	return u
}

// setFieldError is the sanctioned way handwritten extension code sets a
// field error without bypassing public setter behavior (FR-019). Setting a
// new error for a field replaces any previous error for that field.
func (u *User) setFieldError(f UserField, err error) *User {
	if u.errs == nil {
		u.errs = make(map[UserField]error)
	}
	u.errs[f] = err
	return u
}

// clearFieldError is the sanctioned way handwritten extension code clears a
// field error without bypassing public setter behavior (FR-019).
func (u *User) clearFieldError(f UserField) *User {
	delete(u.errs, f)
	return u
}

// Exists reports whether User has ever been persisted.
func (u *User) Exists() bool { return u.state != modelStateNew }

// IsPersisted reports whether User currently has a persisted backing row.
func (u *User) IsPersisted() bool { return u.state == modelStatePersisted }

// IsNew reports whether User has never been persisted.
func (u *User) IsNew() bool { return u.state == modelStateNew }

// IsDeleted reports whether User has been deleted.
func (u *User) IsDeleted() bool { return u.state == modelStateDeleted }

// IsAttached reports whether User is attached to an owning session.
func (u *User) IsAttached() bool { return u.coll != nil }

// IsDetached reports whether User has no owning session.
func (u *User) IsDetached() bool { return !u.IsAttached() }

// Detach returns a copy of User without an owning session.
func (u *User) Detach() *User {
	v := *u
	v.coll = nil
	return &v
}

// Save validates first; inserts if new, does nothing if persisted and
// clean, updates if persisted and dirty. Returns ErrModelDeleted or
// ErrModelDetached if User is deleted or not attached.
func (u *User) Save(ctx context.Context) error {
	if u.state == modelStateDeleted {
		return ErrModelDeleted
	}
	if !u.IsAttached() {
		return ErrModelDetached
	}
	if err := u.Validate(); err != nil {
		return err
	}
	switch {
	case u.state == modelStateNew:
		out, err := u.coll.store.insert(ctx, u.current)
		if err != nil {
			return err
		}
		u.current, u.original = out, out
		u.state = modelStatePersisted
		return nil
	case u.IsClean():
		return nil
	default:
		return ErrOperationNotConfigured
	}
}

// Delete deletes User; idempotent if already deleted. Returns
// ErrModelDetached if User is not attached.
func (u *User) Delete(ctx context.Context) error {
	if u.state == modelStateDeleted {
		return nil
	}
	if !u.IsAttached() {
		return ErrModelDetached
	}
	if u.state == modelStateNew {
		return ErrModelNotPersisted
	}
	return ErrOperationNotConfigured
}

// Refresh re-hydrates User from the database and re-synchronizes its
// original snapshot. Returns ErrModelDeleted or ErrModelDetached if
// User is deleted or not attached.
func (u *User) Refresh(ctx context.Context) error {
	if u.state == modelStateDeleted {
		return ErrModelDeleted
	}
	if !u.IsAttached() {
		return ErrModelDetached
	}
	if u.state == modelStateNew {
		return ErrModelNotPersisted
	}
	return ErrOperationNotConfigured
}

// String renders User for diagnostics, omitting the value of every
// field marked sensitive (FR-014).
func (u *User) String() string {
	fields := []string{
		fmt.Sprintf("ID=%v", u.current.ID),
		fmt.Sprintf("Name=%v", u.current.Name),
	}
	return fmt.Sprintf("User{%s}", strings.Join(fields, ", "))
}
